/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createItemLinkDtoFromDiscriminatorValue, createTaskDtoFromDiscriminatorValue, type ItemLinkDto, type TaskDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemLinkDto400Error}
 */
// @ts-ignore
export function createItemLinkDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItemLinkDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TaskDto400Error}
 */
// @ts-ignore
export function createTaskDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTaskDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemLinkDto400Error(itemLinkDto400Error: Partial<ItemLinkDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { itemLinkDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTaskDto400Error(taskDto400Error: Partial<TaskDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { taskDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Builds and executes requests for operations under /v1/item_links/{id}
 */
export interface Item_linksItemRequestBuilder extends BaseRequestBuilder<Item_linksItemRequestBuilder> {
    /**
     * Delete a Item link by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskDto>}
     * @throws {TaskDto400Error} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskDto | undefined>;
    /**
     * Get a Item link by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ItemLinkDto>}
     * @throws {ItemLinkDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ItemLinkDto | undefined>;
    /**
     * Delete a Item link by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get a Item link by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface ItemLinkDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemLinkDto400Error(writer: SerializationWriter, itemLinkDto400Error: Partial<ItemLinkDto400Error> | undefined | null = {}) : void {
    if (itemLinkDto400Error) {
        writer.writeStringValue("message", itemLinkDto400Error.messageEscaped);
        writer.writeAdditionalData(itemLinkDto400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTaskDto400Error(writer: SerializationWriter, taskDto400Error: Partial<TaskDto400Error> | undefined | null = {}) : void {
    if (taskDto400Error) {
        writer.writeStringValue("message", taskDto400Error.messageEscaped);
        writer.writeAdditionalData(taskDto400Error.additionalData);
    }
}
export interface TaskDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Uri template for the request builder.
 */
export const Item_linksItemRequestBuilderUriTemplate = "{+baseurl}/v1/item_links/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const Item_linksItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: Item_linksItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTaskDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTaskDtoFromDiscriminatorValue,
    },
    get: {
        uriTemplate: Item_linksItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createItemLinkDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createItemLinkDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
