/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSuggestionDtoFromDiscriminatorValue, serializeSuggestionCreateDto, serializeSuggestionDto, type SuggestionCreateDto, type SuggestionDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { SuggestionsItemRequestBuilderNavigationMetadata, SuggestionsItemRequestBuilderRequestsMetadata, type SuggestionsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SuggestionDto400Error}
 */
// @ts-ignore
export function createSuggestionDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSuggestionDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Suggestions400Error}
 */
// @ts-ignore
export function createSuggestions400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSuggestions400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SuggestionsGetResponse}
 */
// @ts-ignore
export function createSuggestionsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSuggestionsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSuggestionDto400Error(suggestionDto400Error: Partial<SuggestionDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { suggestionDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSuggestions400Error(suggestions400Error: Partial<Suggestions400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { suggestions400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSuggestionsGetResponse(suggestionsGetResponse: Partial<SuggestionsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { suggestionsGetResponse.data = n.getCollectionOfObjectValues<SuggestionDto>(createSuggestionDtoFromDiscriminatorValue); },
        "object": n => { suggestionsGetResponse.object = n.getEnumValue<SuggestionsGetResponse_object>(SuggestionsGetResponse_objectObject); },
        "totalElements": n => { suggestionsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSuggestionDto400Error(writer: SerializationWriter, suggestionDto400Error: Partial<SuggestionDto400Error> | undefined | null = {}) : void {
    if (suggestionDto400Error) {
        writer.writeStringValue("message", suggestionDto400Error.messageEscaped);
        writer.writeAdditionalData(suggestionDto400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSuggestions400Error(writer: SerializationWriter, suggestions400Error: Partial<Suggestions400Error> | undefined | null = {}) : void {
    if (suggestions400Error) {
        writer.writeStringValue("message", suggestions400Error.messageEscaped);
        writer.writeAdditionalData(suggestions400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSuggestionsGetResponse(writer: SerializationWriter, suggestionsGetResponse: Partial<SuggestionsGetResponse> | undefined | null = {}) : void {
    if (suggestionsGetResponse) {
        writer.writeCollectionOfObjectValues<SuggestionDto>("data", suggestionsGetResponse.data, serializeSuggestionDto);
        writer.writeEnumValue<SuggestionsGetResponse_object>("object", suggestionsGetResponse.object);
        writer.writeNumberValue("totalElements", suggestionsGetResponse.totalElements);
        writer.writeAdditionalData(suggestionsGetResponse.additionalData);
    }
}
export interface SuggestionDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Suggestions400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface SuggestionsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: SuggestionDto[] | null;
    /**
     * The object property
     */
    object?: SuggestionsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type SuggestionsGetResponse_object = (typeof SuggestionsGetResponse_objectObject)[keyof typeof SuggestionsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/suggestions
 */
export interface SuggestionsRequestBuilder extends BaseRequestBuilder<SuggestionsRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.suggestions.item collection
     * @param id Unique identifier of the item
     * @returns {SuggestionsItemRequestBuilder}
     */
     byId(id: string) : SuggestionsItemRequestBuilder;
    /**
     * Get a list of Suggestion
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SuggestionsGetResponse>}
     * @throws {Suggestions400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<SuggestionsRequestBuilderGetQueryParameters> | undefined) : Promise<SuggestionsGetResponse | undefined>;
    /**
     * Create a Suggestion
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SuggestionDto>}
     * @throws {SuggestionDto400Error} error when the service returns a 400 status code
     */
     post(body: SuggestionCreateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SuggestionDto | undefined>;
    /**
     * Get a list of Suggestion
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SuggestionsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a Suggestion
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SuggestionCreateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a list of Suggestion
 */
export interface SuggestionsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
}
/**
 * Uri template for the request builder.
 */
export const SuggestionsRequestBuilderUriTemplate = "{+baseurl}/v1/suggestions{?page*,size*,sort*,sortOrder*}";
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
export const SuggestionsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SuggestionsRequestBuilderNavigationMetadata: Record<Exclude<keyof SuggestionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: SuggestionsItemRequestBuilderRequestsMetadata,
        navigationMetadata: SuggestionsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SuggestionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SuggestionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createSuggestions400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSuggestionsGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SuggestionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createSuggestionDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSuggestionDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSuggestionCreateDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
