/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCommentThreadDtoFromDiscriminatorValue, serializeCommentThreadDto, serializeCommentThreadReplyCreateDto, type CommentThreadDto, type CommentThreadReplyCreateDto } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/comment_threads/{id}/add-reply
 */
export interface AddReplyRequestBuilder extends BaseRequestBuilder<AddReplyRequestBuilder> {
    /**
     * Add a reply to a comment thread
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CommentThreadDto>}
     */
     post(body: CommentThreadReplyCreateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CommentThreadDto | undefined>;
    /**
     * Add a reply to a comment thread
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CommentThreadReplyCreateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AddReplyRequestBuilderUriTemplate = "{+baseurl}/v1/comment_threads/{id}/add-reply";
/**
 * Metadata for all the requests in the request builder.
 */
export const AddReplyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AddReplyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createCommentThreadDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCommentThreadReplyCreateDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
