/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAccountDtoFromDiscriminatorValue, serializeAccountDto, type AccountDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { AccountsItemRequestBuilderRequestsMetadata, type AccountsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface Accounts400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface AccountsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: AccountDto[] | null;
    /**
     * The object property
     */
    object?: AccountsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type AccountsGetResponse_object = (typeof AccountsGetResponse_objectObject)[keyof typeof AccountsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/accounts
 */
export interface AccountsRequestBuilder extends BaseRequestBuilder<AccountsRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.accounts.item collection
     * @param id Unique identifier of the item
     * @returns {AccountsItemRequestBuilder}
     */
     byId(id: string) : AccountsItemRequestBuilder;
    /**
     * Get a list of Account
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AccountsGetResponse>}
     * @throws {Accounts400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<AccountsRequestBuilderGetQueryParameters> | undefined) : Promise<AccountsGetResponse | undefined>;
    /**
     * Get a list of Account
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AccountsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Account
 */
export interface AccountsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Accounts400Error}
 */
// @ts-ignore
export function createAccounts400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccounts400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccountsGetResponse}
 */
// @ts-ignore
export function createAccountsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccountsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccounts400Error(accounts400Error: Partial<Accounts400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { accounts400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccountsGetResponse(accountsGetResponse: Partial<AccountsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { accountsGetResponse.data = n.getCollectionOfObjectValues<AccountDto>(createAccountDtoFromDiscriminatorValue); },
        "object": n => { accountsGetResponse.object = n.getEnumValue<AccountsGetResponse_object>(AccountsGetResponse_objectObject); },
        "totalElements": n => { accountsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccounts400Error(writer: SerializationWriter, accounts400Error: Partial<Accounts400Error> | undefined | null = {}) : void {
    if (accounts400Error) {
        writer.writeStringValue("message", accounts400Error.messageEscaped);
        writer.writeAdditionalData(accounts400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccountsGetResponse(writer: SerializationWriter, accountsGetResponse: Partial<AccountsGetResponse> | undefined | null = {}) : void {
    if (accountsGetResponse) {
        writer.writeCollectionOfObjectValues<AccountDto>("data", accountsGetResponse.data, serializeAccountDto);
        writer.writeEnumValue<AccountsGetResponse_object>("object", accountsGetResponse.object);
        writer.writeNumberValue("totalElements", accountsGetResponse.totalElements);
        writer.writeAdditionalData(accountsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const AccountsRequestBuilderUriTemplate = "{+baseurl}/v1/accounts{?page*,size*,sort*,sortOrder*}";
export const AccountsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AccountsRequestBuilderNavigationMetadata: Record<Exclude<keyof AccountsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: AccountsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AccountsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AccountsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAccounts400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAccountsGetResponseFromDiscriminatorValue,
    },
};
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
/* tslint:enable */
/* eslint-enable */
