/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCommentThreadDtoFromDiscriminatorValue, serializeCommentThreadDto, serializeCommentThreadUpdateDto, type CommentThreadDto, type CommentThreadUpdateDto } from '../../../models/index.js';
// @ts-ignore
import { AddReplyRequestBuilderRequestsMetadata, type AddReplyRequestBuilder } from './addReply/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/comment_threads/{id}
 */
export interface Comment_threadsItemRequestBuilder extends BaseRequestBuilder<Comment_threadsItemRequestBuilder> {
    /**
     * The addReply property
     */
    get addReply(): AddReplyRequestBuilder;
    /**
     * Get a Comment Thread by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CommentThreadDto>}
     * @throws {CommentThreadDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CommentThreadDto | undefined>;
    /**
     * Patch a Comment Thread
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CommentThreadDto>}
     * @throws {CommentThreadDto400Error} error when the service returns a 400 status code
     */
     patch(body: CommentThreadUpdateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CommentThreadDto | undefined>;
    /**
     * Get a Comment Thread by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Patch a Comment Thread
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: CommentThreadUpdateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface CommentThreadDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CommentThreadDto400Error}
 */
// @ts-ignore
export function createCommentThreadDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCommentThreadDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCommentThreadDto400Error(commentThreadDto400Error: Partial<CommentThreadDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { commentThreadDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCommentThreadDto400Error(writer: SerializationWriter, commentThreadDto400Error: Partial<CommentThreadDto400Error> | undefined | null = {}) : void {
    if (commentThreadDto400Error) {
        writer.writeStringValue("message", commentThreadDto400Error.messageEscaped);
        writer.writeAdditionalData(commentThreadDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Comment_threadsItemRequestBuilderUriTemplate = "{+baseurl}/v1/comment_threads/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Comment_threadsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof Comment_threadsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    addReply: {
        requestsMetadata: AddReplyRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Comment_threadsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Comment_threadsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createCommentThreadDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCommentThreadDtoFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: Comment_threadsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createCommentThreadDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCommentThreadDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCommentThreadUpdateDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
