/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CommentThreadSubscriberDto {
    'object': CommentThreadSubscriberDtoObjectEnum;
    'id': string;
    'createdAt': string;
    'updatedAt': string;
    'userId': string;
    'accountId': string;
    'commentThreadId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "CommentThreadSubscriberDtoObjectEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "commentThreadId",
            "baseName": "commentThreadId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommentThreadSubscriberDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CommentThreadSubscriberDtoObjectEnum {
    CommentThreadSubscriber = 'comment_thread_subscriber'
}

