/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentThreadReplyDTO } from '../models/CommentThreadReplyDTO';
import { HttpFile } from '../http/http';

export class CommentThreadDto {
    'object': CommentThreadDtoObjectEnum;
    'id': string;
    'createdAt': string;
    'updatedAt': string;
    'comments': Array<CommentThreadReplyDTO>;
    'isClosed': boolean;
    'userId': string;
    'accountId': string;
    'accountAssigneesId': Array<string>;
    'subscribersId': Array<string>;
    'type': CommentThreadDtoTypeEnum;
    'targetId': string;
    'targetType': CommentThreadDtoTargetTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "CommentThreadDtoObjectEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<CommentThreadReplyDTO>",
            "format": ""
        },
        {
            "name": "isClosed",
            "baseName": "isClosed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountAssigneesId",
            "baseName": "accountAssigneesId",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "subscribersId",
            "baseName": "subscribersId",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CommentThreadDtoTypeEnum",
            "format": ""
        },
        {
            "name": "targetId",
            "baseName": "targetId",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetType",
            "baseName": "targetType",
            "type": "CommentThreadDtoTargetTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommentThreadDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CommentThreadDtoObjectEnum {
    CommentThread = 'comment_thread'
}
export enum CommentThreadDtoTypeEnum {
    Default = 'DEFAULT',
    System = 'SYSTEM'
}
export enum CommentThreadDtoTargetTypeEnum {
    Schedule = 'schedule',
    PlanExecution = 'plan_execution',
    Execution = 'execution',
    Account = 'account',
    AccountPlan = 'account_plan',
    AccountPlanFeature = 'account_plan_feature',
    AccountApiClientInfo = 'account_api_client_info',
    User = 'user',
    Member = 'member',
    Table = 'table',
    UserHasAccount = 'user_has_account',
    ContainerLinkEntity = 'container_link_entity',
    GlobalMessage = 'global_message',
    Group = 'group',
    Screen = 'screen',
    ScreenDetail = 'screen_detail',
    PlEmployee = 'pl_employee',
    ProjectCategory = 'project_category',
    Activity = 'activity',
    Pipeline = 'pipeline',
    JobInstance = 'job_instance',
    Job = 'job',
    TaskExternal = 'task_external',
    WorkflowDefinition = 'workflow_definition',
    FileRef = 'file_ref',
    AccountInvitation = 'account_invitation',
    AccountRelation = 'account_relation',
    AccountContactGroup = 'account_contact_group',
    RowData = 'row_data',
    Suggestion = 'suggestion',
    SuggestionCreation = 'suggestion_creation',
    ItemSuggestion = 'item_suggestion',
    ItemPublication = 'item_publication',
    Partition = 'partition',
    Level = 'level',
    Item = 'item',
    ItemLink = 'item_link',
    Permission = 'permission',
    ConditionalFormatting = 'conditionalFormatting',
    ConditionalFormattingStatus = 'conditionalFormattingStatus',
    ConditionalFormattingRule = 'conditionalFormattingRule',
    UserTableSavedSearch = 'user_table_saved_search',
    FieldValue = 'fieldValue',
    Field = 'field',
    Section = 'section',
    GridColumn = 'grid_column',
    TableConditionalField = 'table_conditional_field',
    TableConditionalFieldValue = 'table_conditional_field_value',
    ItemConditionalFormattingRule = 'item_conditional_formatting_rule',
    AccountHasTable = 'account_has_table',
    TableLink = 'table_link',
    MappingRule = 'mapping_rule',
    MappingField = 'mapping_field',
    FeatureFlag = 'feature_flag',
    TableQuickImportSettings = 'table_quick_import_settings',
    ItemImportReport = 'item_import_report',
    FormulaRule = 'formula_rule',
    DataFactoryVariable = 'data_factory_variable',
    DataFactoryVariableOverload = 'data_factory_variable_overload',
    FieldValueByFormulaRule = 'field_value_by_formula_rule',
    FieldValueWhitelist = 'field_value_whitelist',
    CommentThread = 'comment_thread',
    CommentThreadDto = 'comment_thread_dto',
    CommentThreadAssignee = 'comment_thread_assignee',
    CommentThreadSubscriber = 'comment_thread_subscriber',
    YubaLog = 'yuba_log',
    YubaLogGroupMetadata = 'yuba_log_group_metadata',
    AuditLog = 'audit_log',
    Suffix = 'suffix',
    ResetPassword = 'reset_password',
    TestType = 'test_type',
    GenericMockData = 'generic_mock_data',
    Dashboard = 'dashboard'
}

