/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobLocalDto } from '../models/JobLocalDto';
import { JobPeriodicityDto } from '../models/JobPeriodicityDto';
import { JobTaskDto } from '../models/JobTaskDto';
import { HttpFile } from '../http/http';

export class CreateJobDto {
    'key': string;
    'pipelineId': string;
    'projectId': string;
    'title': string;
    'periodicity': Array<JobPeriodicityDto>;
    'status': CreateJobDtoStatusEnum;
    'titleLocal': JobLocalDto;
    'description': string;
    'descriptionLocal': JobLocalDto;
    'output': any;
    'tasks': Array<JobTaskDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "pipelineId",
            "baseName": "pipelineId",
            "type": "string",
            "format": ""
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "periodicity",
            "baseName": "periodicity",
            "type": "Array<JobPeriodicityDto>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateJobDtoStatusEnum",
            "format": ""
        },
        {
            "name": "titleLocal",
            "baseName": "titleLocal",
            "type": "JobLocalDto",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionLocal",
            "baseName": "descriptionLocal",
            "type": "JobLocalDto",
            "format": ""
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "any",
            "format": ""
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<JobTaskDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateJobDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CreateJobDtoStatusEnum {
    Draft = 'DRAFT',
    Production = 'PRODUCTION',
    Deprecated = 'DEPRECATED',
    Archived = 'ARCHIVED',
    Removed = 'REMOVED'
}

