/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentThreadSubscriberDto } from '../models/CommentThreadSubscriberDto';
import { HttpFile } from '../http/http';

export class GetCommentThreadSubscribers200Response {
    'object': GetCommentThreadSubscribers200ResponseObjectEnum;
    'totalElements': number;
    'data': Array<CommentThreadSubscriberDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "GetCommentThreadSubscribers200ResponseObjectEnum",
            "format": ""
        },
        {
            "name": "totalElements",
            "baseName": "totalElements",
            "type": "number",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<CommentThreadSubscriberDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCommentThreadSubscribers200Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GetCommentThreadSubscribers200ResponseObjectEnum {
    List = 'list'
}

