/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HighOrderQueryDTO } from '../models/HighOrderQueryDTO';
import { HttpFile } from '../http/http';

export class HighOrderQueryDTOQueriesInner {
    'queries': Array<HighOrderQueryDTOQueriesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "queries",
            "baseName": "queries",
            "type": "Array<HighOrderQueryDTOQueriesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HighOrderQueryDTOQueriesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

