/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemFieldFile } from '../models/ItemFieldFile';
import { ItemFieldMultipleSelectWithCommentAndQuantity } from '../models/ItemFieldMultipleSelectWithCommentAndQuantity';
import { ItemFieldSimpleNumber } from '../models/ItemFieldSimpleNumber';
import { ItemFieldSimpleString } from '../models/ItemFieldSimpleString';
import { ItemFieldSimpleStringArray } from '../models/ItemFieldSimpleStringArray';
import { HttpFile } from '../http/http';

export class ItemFieldDTOValue {
    'data': string;
    'suffix'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "suffix",
            "baseName": "suffix",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemFieldDTOValue.attributeTypeMap;
    }

    public constructor() {
    }
}

