/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ItemLinkCreateDto {
    'object': ItemLinkCreateDtoObjectEnum;
    'fromItemId': string;
    'toItemId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "ItemLinkCreateDtoObjectEnum",
            "format": ""
        },
        {
            "name": "fromItemId",
            "baseName": "fromItemId",
            "type": "string",
            "format": ""
        },
        {
            "name": "toItemId",
            "baseName": "toItemId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemLinkCreateDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ItemLinkCreateDtoObjectEnum {
    ItemLinkCreate = 'item_link_create'
}

