/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemFieldFileData } from '../models/ItemFieldFileData';
import { HttpFile } from '../http/http';

export class ItemFieldFile {
    'data': ItemFieldFileData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "ItemFieldFileData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemFieldFile.attributeTypeMap;
    }

    public constructor() {
    }
}

