/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemFieldSimpleString } from '../models/ItemFieldSimpleString';
import { HttpFile } from '../http/http';

export class ItemFieldStringDTO {
    'value': ItemFieldSimpleString;
    'id': string;
    'type': ItemFieldStringDTOTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "ItemFieldSimpleString",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ItemFieldStringDTOTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemFieldStringDTO.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ItemFieldStringDTOTypeEnum {
    Identifier = 'IDENTIFIER',
    Classification = 'CLASSIFICATION',
    SingleLineText = 'SINGLE_LINE_TEXT',
    LongText = 'LONG_TEXT',
    Number = 'NUMBER',
    Date = 'DATE',
    DateTime = 'DATE_TIME',
    HtmlText = 'HTML_TEXT',
    Image = 'IMAGE',
    Attachment = 'ATTACHMENT',
    SingleSelect = 'SINGLE_SELECT',
    MultipleSelect = 'MULTIPLE_SELECT',
    MultipleSelectQuantified = 'MULTIPLE_SELECT_QUANTIFIED',
    MultipleSelectQuantifiedWithComments = 'MULTIPLE_SELECT_QUANTIFIED_WITH_COMMENTS',
    MultipleSelectWithComments = 'MULTIPLE_SELECT_WITH_COMMENTS',
    ConditionalField = 'CONDITIONAL_FIELD'
}

