/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ItemMetadataDTO {
    'createdAt': string;
    'updatedAt': string;
    'tableId': string;
    'tableKey': string;
    'tableOwnerAccountId': string;
    'levelId': string;
    'levelKey': string;
    'partitionId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "tableId",
            "baseName": "tableId",
            "type": "string",
            "format": ""
        },
        {
            "name": "tableKey",
            "baseName": "tableKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "tableOwnerAccountId",
            "baseName": "tableOwnerAccountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "levelId",
            "baseName": "levelId",
            "type": "string",
            "format": ""
        },
        {
            "name": "levelKey",
            "baseName": "levelKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "partitionId",
            "baseName": "partitionId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemMetadataDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

