/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobExecutionInfoDto } from '../models/JobExecutionInfoDto';
import { HttpFile } from '../http/http';

export class JobExecutionDto {
    'object': JobExecutionDtoObjectEnum;
    'id': string;
    'jobId': string;
    'info'?: JobExecutionInfoDto;
    'createdAt'?: string;
    'updatedAt'?: string;
    'endedAt'?: string;
    'startedAt'?: string;
    'pipelineId'?: string;
    'status': JobExecutionDtoStatusEnum;
    'output'?: any;
    'input': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "JobExecutionDtoObjectEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobId",
            "baseName": "jobId",
            "type": "string",
            "format": ""
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "JobExecutionInfoDto",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "endedAt",
            "baseName": "endedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "pipelineId",
            "baseName": "pipelineId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "JobExecutionDtoStatusEnum",
            "format": ""
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "any",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobExecutionDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum JobExecutionDtoObjectEnum {
    JobExecution = 'job_execution'
}
export enum JobExecutionDtoStatusEnum {
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    CompletedWithErrors = 'COMPLETED_WITH_ERRORS',
    TimedOut = 'TIMED_OUT',
    Failed = 'FAILED',
    Pending = 'PENDING',
    Scheduled = 'SCHEDULED',
    Terminated = 'TERMINATED',
    InProgress = 'IN_PROGRESS',
    Unknown = 'UNKNOWN',
    Removed = 'REMOVED',
    Queued = 'QUEUED',
    Paused = 'PAUSED',
    UserError = 'USER_ERROR'
}

