/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobPeriodicityDto {
    'isEnabled': boolean;
    'cronExpression': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isEnabled",
            "baseName": "isEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "cronExpression",
            "baseName": "cronExpression",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobPeriodicityDto.attributeTypeMap;
    }

    public constructor() {
    }
}

