/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobTaskDto {
    'name': string;
    'taskReferenceName': string;
    'isOptional'?: boolean;
    'type': string;
    'description'?: string;
    'input'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskReferenceName",
            "baseName": "taskReferenceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "isOptional",
            "baseName": "isOptional",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobTaskDto.attributeTypeMap;
    }

    public constructor() {
    }
}

