/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PatchPublicationDto {
    'status': PatchPublicationDtoStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "PatchPublicationDtoStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatchPublicationDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PatchPublicationDtoStatusEnum {
    Sent = 'SENT',
    Received = 'RECEIVED',
    Rejected = 'REJECTED'
}

