/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemFieldDTO } from '../models/ItemFieldDTO';
import { HttpFile } from '../http/http';

export class PublicationDto {
    'object': PublicationDtoObjectEnum;
    'id': string;
    'createdAt': string;
    'updatedAt': string;
    'sentAt': string;
    'tableId': string;
    'partitionId': string;
    'screenId': string;
    'fromItemId': string;
    'toAccountId': string;
    'fields'?: Array<ItemFieldDTO>;
    'status': PublicationDtoStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "PublicationDtoObjectEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "sentAt",
            "baseName": "sentAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "tableId",
            "baseName": "tableId",
            "type": "string",
            "format": ""
        },
        {
            "name": "partitionId",
            "baseName": "partitionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "screenId",
            "baseName": "screenId",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromItemId",
            "baseName": "fromItemId",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAccountId",
            "baseName": "toAccountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<ItemFieldDTO>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PublicationDtoStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicationDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PublicationDtoObjectEnum {
    Publication = 'publication'
}
export enum PublicationDtoStatusEnum {
    Sent = 'SENT',
    Received = 'RECEIVED',
    Rejected = 'REJECTED'
}

