/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HighOrderQueryDTO } from '../models/HighOrderQueryDTO';
import { HighOrderQueryDTOQueriesInner } from '../models/HighOrderQueryDTOQueriesInner';
import { LowOrderQueryDTO } from '../models/LowOrderQueryDTO';
import { HttpFile } from '../http/http';

export class QueryDTO {
    'value': any | null;
    'field': string;
    'caseSensitive'?: boolean;
    'type': QueryDTOTypeEnum;
    'queries': Array<HighOrderQueryDTOQueriesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "any",
            "format": ""
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseSensitive",
            "baseName": "caseSensitive",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "QueryDTOTypeEnum",
            "format": ""
        },
        {
            "name": "queries",
            "baseName": "queries",
            "type": "Array<HighOrderQueryDTOQueriesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QueryDTO.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum QueryDTOTypeEnum {
    Eq = 'eq',
    Search = 'search',
    And = 'and',
    Or = 'or',
    In = 'in',
    NotIn = 'notIn',
    True = 'true',
    False = 'false',
    Greater = 'greater',
    GreaterOrEqual = 'greaterOrEqual',
    Lower = 'lower',
    LowerOrEqual = 'lowerOrEqual',
    IsNull = 'isNull',
    LocalizedSearch = 'localizedSearch'
}

