/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ScreenDto {
    'createdAt': string;
    'updatedAt': string;
    'id': string;
    'key': string;
    'position': number;
    'title': string;
    'lineHeight': ScreenDtoLineHeightEnum;
    'status': ScreenDtoStatusEnum;
    'description': string;
    'tableId': string;
    'levelId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "lineHeight",
            "baseName": "lineHeight",
            "type": "ScreenDtoLineHeightEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ScreenDtoStatusEnum",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "tableId",
            "baseName": "tableId",
            "type": "string",
            "format": ""
        },
        {
            "name": "levelId",
            "baseName": "levelId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScreenDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ScreenDtoLineHeightEnum {
    ExtraShort = 'EXTRA_SHORT',
    Short = 'SHORT',
    Medium = 'MEDIUM',
    Tall = 'TALL',
    ExtraTall = 'EXTRA_TALL'
}
export enum ScreenDtoStatusEnum {
    Active = 'ACTIVE',
    Archived = 'ARCHIVED',
    Deleted = 'DELETED'
}

