/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemFieldDTO } from '../models/ItemFieldDTO';
import { SuggestionDeletedFieldDTO } from '../models/SuggestionDeletedFieldDTO';
import { HttpFile } from '../http/http';

export class SuggestionDto {
    'object': SuggestionDtoObjectEnum;
    'id': string;
    'screenId': string;
    'createdAt': string;
    'updatedAt': string;
    'fromItemId': string;
    'toItemId': string;
    'emitterName': string;
    'fields'?: Array<ItemFieldDTO>;
    'deletedFields': Array<SuggestionDeletedFieldDTO>;
    'isAcknowledged': boolean;
    'hasCreatedItem': boolean;
    'fromAccountId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "SuggestionDtoObjectEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "screenId",
            "baseName": "screenId",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromItemId",
            "baseName": "fromItemId",
            "type": "string",
            "format": ""
        },
        {
            "name": "toItemId",
            "baseName": "toItemId",
            "type": "string",
            "format": ""
        },
        {
            "name": "emitterName",
            "baseName": "emitterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<ItemFieldDTO>",
            "format": ""
        },
        {
            "name": "deletedFields",
            "baseName": "deletedFields",
            "type": "Array<SuggestionDeletedFieldDTO>",
            "format": ""
        },
        {
            "name": "isAcknowledged",
            "baseName": "isAcknowledged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasCreatedItem",
            "baseName": "hasCreatedItem",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "fromAccountId",
            "baseName": "fromAccountId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuggestionDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SuggestionDtoObjectEnum {
    Suggestion = 'suggestion'
}

