/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemDtoFieldsInner } from '../models/ItemDtoFieldsInner';
import { HttpFile } from '../http/http';

export class SuggestionCreateDto {
    'object': SuggestionCreateDtoObjectEnum;
    'itemId': string;
    'screenId': string;
    'hasCreatedItem': boolean;
    'publicationId'?: string;
    'emitterName'?: string;
    'fields'?: Array<ItemDtoFieldsInner>;
    'deletedFieldsIds'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "SuggestionCreateDtoObjectEnum",
            "format": ""
        },
        {
            "name": "itemId",
            "baseName": "itemId",
            "type": "string",
            "format": ""
        },
        {
            "name": "screenId",
            "baseName": "screenId",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasCreatedItem",
            "baseName": "hasCreatedItem",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "publicationId",
            "baseName": "publicationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "emitterName",
            "baseName": "emitterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<ItemDtoFieldsInner>",
            "format": ""
        },
        {
            "name": "deletedFieldsIds",
            "baseName": "deletedFieldsIds",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuggestionCreateDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SuggestionCreateDtoObjectEnum {
    SuggestionCreate = 'suggestion-create'
}

