/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TaskExecutionDto {
    'id': string;
    'object': TaskExecutionDtoObjectEnum;
    'createdAt': string;
    'updatedAt': string;
    'input': any;
    'output': any;
    'status': TaskExecutionDtoStatusEnum;
    'taskId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "TaskExecutionDtoObjectEnum",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "any",
            "format": ""
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "any",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskExecutionDtoStatusEnum",
            "format": ""
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskExecutionDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskExecutionDtoObjectEnum {
    TaskExecution = 'task_execution'
}
export enum TaskExecutionDtoStatusEnum {
    Scheduled = 'SCHEDULED',
    InProgress = 'IN_PROGRESS',
    Cancelled = 'CANCELLED',
    Failed = 'FAILED',
    Completed = 'COMPLETED'
}

