/**
 * Product-Live API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.48.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskDtoKey } from '../models/TaskDtoKey';
import { HttpFile } from '../http/http';

export class UpdateTaskDto {
    'id': string;
    'key': string;
    'description': string;
    'retryCount': number;
    'timeoutSeconds': number;
    'timeoutPolicy': UpdateTaskDtoTimeoutPolicyEnum;
    'retryLogic': UpdateTaskDtoRetryLogicEnum;
    'retryDelaySeconds': number;
    'responseTimeoutSeconds': number;
    'concurrentExecLimit': number;
    'pollTimeoutSeconds': number;
    'backoffScaleFactor': number;
    'inputKeys': Array<TaskDtoKey>;
    'outputKeys': Array<TaskDtoKey>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "retryCount",
            "baseName": "retryCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "timeoutSeconds",
            "baseName": "timeoutSeconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "timeoutPolicy",
            "baseName": "timeoutPolicy",
            "type": "UpdateTaskDtoTimeoutPolicyEnum",
            "format": ""
        },
        {
            "name": "retryLogic",
            "baseName": "retryLogic",
            "type": "UpdateTaskDtoRetryLogicEnum",
            "format": ""
        },
        {
            "name": "retryDelaySeconds",
            "baseName": "retryDelaySeconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "responseTimeoutSeconds",
            "baseName": "responseTimeoutSeconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "concurrentExecLimit",
            "baseName": "concurrentExecLimit",
            "type": "number",
            "format": ""
        },
        {
            "name": "pollTimeoutSeconds",
            "baseName": "pollTimeoutSeconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "backoffScaleFactor",
            "baseName": "backoffScaleFactor",
            "type": "number",
            "format": ""
        },
        {
            "name": "inputKeys",
            "baseName": "inputKeys",
            "type": "Array<TaskDtoKey>",
            "format": ""
        },
        {
            "name": "outputKeys",
            "baseName": "outputKeys",
            "type": "Array<TaskDtoKey>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateTaskDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UpdateTaskDtoTimeoutPolicyEnum {
    Retry = 'RETRY',
    TimeOutWf = 'TIME_OUT_WF',
    AlertOnly = 'ALERT_ONLY'
}
export enum UpdateTaskDtoRetryLogicEnum {
    Fixed = 'FIXED',
    ExponentialBackoff = 'EXPONENTIAL_BACKOFF'
}

