/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLevelDtoFromDiscriminatorValue, type LevelDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LevelDto400Error}
 */
// @ts-ignore
export function createLevelDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLevelDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLevelDto400Error(levelDto400Error: Partial<LevelDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { levelDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface LevelDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/levels/{id}
 */
export interface LevelsItemRequestBuilder extends BaseRequestBuilder<LevelsItemRequestBuilder> {
    /**
     * Get a Level by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LevelDto>}
     * @throws {LevelDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LevelDto | undefined>;
    /**
     * Get a Level by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLevelDto400Error(writer: SerializationWriter, levelDto400Error: Partial<LevelDto400Error> | undefined | null = {}) : void {
    if (levelDto400Error) {
        writer.writeStringValue("message", levelDto400Error.messageEscaped);
        writer.writeAdditionalData(levelDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const LevelsItemRequestBuilderUriTemplate = "{+baseurl}/v1/levels/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const LevelsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LevelsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createLevelDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLevelDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
