/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createItemDtoFromDiscriminatorValue, serializeItemDto, type ItemDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderNavigationMetadata, FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { ItemsItemRequestBuilderRequestsMetadata, type ItemsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Items400Error}
 */
// @ts-ignore
export function createItems400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItems400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemsGetResponse}
 */
// @ts-ignore
export function createItemsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItemsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItems400Error(items400Error: Partial<Items400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { items400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemsGetResponse(itemsGetResponse: Partial<ItemsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { itemsGetResponse.data = n.getCollectionOfObjectValues<ItemDto>(createItemDtoFromDiscriminatorValue); },
        "object": n => { itemsGetResponse.object = n.getEnumValue<ItemsGetResponse_object>(ItemsGetResponse_objectObject); },
        "totalElements": n => { itemsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export interface Items400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface ItemsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: ItemDto[] | null;
    /**
     * The object property
     */
    object?: ItemsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type ItemsGetResponse_object = (typeof ItemsGetResponse_objectObject)[keyof typeof ItemsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/items
 */
export interface ItemsRequestBuilder extends BaseRequestBuilder<ItemsRequestBuilder> {
    /**
     * The find property
     * @deprecated 
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.items.item collection
     * @param id Unique identifier of the item
     * @returns {ItemsItemRequestBuilder}
     */
     byId(id: string) : ItemsItemRequestBuilder;
    /**
     * Get a list of Item
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ItemsGetResponse>}
     * @throws {Items400Error} error when the service returns a 400 status code
     * @deprecated 
     */
     get(requestConfiguration?: RequestConfiguration<ItemsRequestBuilderGetQueryParameters> | undefined) : Promise<ItemsGetResponse | undefined>;
    /**
     * Get a list of Item
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated 
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ItemsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Item
 */
export interface ItemsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItems400Error(writer: SerializationWriter, items400Error: Partial<Items400Error> | undefined | null = {}) : void {
    if (items400Error) {
        writer.writeStringValue("message", items400Error.messageEscaped);
        writer.writeAdditionalData(items400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemsGetResponse(writer: SerializationWriter, itemsGetResponse: Partial<ItemsGetResponse> | undefined | null = {}) : void {
    if (itemsGetResponse) {
        writer.writeCollectionOfObjectValues<ItemDto>("data", itemsGetResponse.data, serializeItemDto);
        writer.writeEnumValue<ItemsGetResponse_object>("object", itemsGetResponse.object);
        writer.writeNumberValue("totalElements", itemsGetResponse.totalElements);
        writer.writeAdditionalData(itemsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const ItemsRequestBuilderUriTemplate = "{+baseurl}/v1/items{?page*,size*}";
export const ItemsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ItemsRequestBuilderNavigationMetadata: Record<Exclude<keyof ItemsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ItemsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
        navigationMetadata: FindRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ItemsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ItemsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createItems400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createItemsGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
