/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSectionDtoFromDiscriminatorValue, type SectionDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SectionDto400Error}
 */
// @ts-ignore
export function createSectionDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSectionDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSectionDto400Error(sectionDto400Error: Partial<SectionDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { sectionDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface SectionDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/sections/{id}
 */
export interface SectionsItemRequestBuilder extends BaseRequestBuilder<SectionsItemRequestBuilder> {
    /**
     * Get a Section by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SectionDto>}
     * @throws {SectionDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SectionDto | undefined>;
    /**
     * Get a Section by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSectionDto400Error(writer: SerializationWriter, sectionDto400Error: Partial<SectionDto400Error> | undefined | null = {}) : void {
    if (sectionDto400Error) {
        writer.writeStringValue("message", sectionDto400Error.messageEscaped);
        writer.writeAdditionalData(sectionDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const SectionsItemRequestBuilderUriTemplate = "{+baseurl}/v1/sections/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const SectionsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SectionsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createSectionDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSectionDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
