/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAccountDtoFromDiscriminatorValue, type AccountDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AccountDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/accounts/{id}
 */
export interface AccountsItemRequestBuilder extends BaseRequestBuilder<AccountsItemRequestBuilder> {
    /**
     * Get a Account by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AccountDto>}
     * @throws {AccountDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AccountDto | undefined>;
    /**
     * Get a Account by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccountDto400Error}
 */
// @ts-ignore
export function createAccountDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccountDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccountDto400Error(accountDto400Error: Partial<AccountDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { accountDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccountDto400Error(writer: SerializationWriter, accountDto400Error: Partial<AccountDto400Error> | undefined | null = {}) : void {
    if (accountDto400Error) {
        writer.writeStringValue("message", accountDto400Error.messageEscaped);
        writer.writeAdditionalData(accountDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const AccountsItemRequestBuilderUriTemplate = "{+baseurl}/v1/accounts/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const AccountsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AccountsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAccountDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAccountDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
