/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFieldDtoFromDiscriminatorValue, serializeFieldDto, type FieldDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { FieldsItemRequestBuilderRequestsMetadata, type FieldsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Fields400Error}
 */
// @ts-ignore
export function createFields400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFields400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FieldsGetResponse}
 */
// @ts-ignore
export function createFieldsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFieldsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFields400Error(fields400Error: Partial<Fields400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { fields400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFieldsGetResponse(fieldsGetResponse: Partial<FieldsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { fieldsGetResponse.data = n.getCollectionOfObjectValues<FieldDto>(createFieldDtoFromDiscriminatorValue); },
        "object": n => { fieldsGetResponse.object = n.getEnumValue<FieldsGetResponse_object>(FieldsGetResponse_objectObject); },
        "totalElements": n => { fieldsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export interface Fields400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface FieldsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: FieldDto[] | null;
    /**
     * The object property
     */
    object?: FieldsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type FieldsGetResponse_object = (typeof FieldsGetResponse_objectObject)[keyof typeof FieldsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/fields
 */
export interface FieldsRequestBuilder extends BaseRequestBuilder<FieldsRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.fields.item collection
     * @param id Unique identifier of the item
     * @returns {FieldsItemRequestBuilder}
     */
     byId(id: string) : FieldsItemRequestBuilder;
    /**
     * Get a list of Field
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FieldsGetResponse>}
     * @throws {Fields400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<FieldsRequestBuilderGetQueryParameters> | undefined) : Promise<FieldsGetResponse | undefined>;
    /**
     * Get a list of Field
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<FieldsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Field
 */
export interface FieldsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
    tableId?: string;
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFields400Error(writer: SerializationWriter, fields400Error: Partial<Fields400Error> | undefined | null = {}) : void {
    if (fields400Error) {
        writer.writeStringValue("message", fields400Error.messageEscaped);
        writer.writeAdditionalData(fields400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFieldsGetResponse(writer: SerializationWriter, fieldsGetResponse: Partial<FieldsGetResponse> | undefined | null = {}) : void {
    if (fieldsGetResponse) {
        writer.writeCollectionOfObjectValues<FieldDto>("data", fieldsGetResponse.data, serializeFieldDto);
        writer.writeEnumValue<FieldsGetResponse_object>("object", fieldsGetResponse.object);
        writer.writeNumberValue("totalElements", fieldsGetResponse.totalElements);
        writer.writeAdditionalData(fieldsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const FieldsRequestBuilderUriTemplate = "{+baseurl}/v1/fields?tableId={tableId}{&page*,size*,sort*,sortOrder*}";
export const FieldsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FieldsRequestBuilderNavigationMetadata: Record<Exclude<keyof FieldsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: FieldsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const FieldsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FieldsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFields400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFieldsGetResponseFromDiscriminatorValue,
    },
};
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
/* tslint:enable */
/* eslint-enable */
