/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createScreenDtoFromDiscriminatorValue, type ScreenDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ScreenDto400Error}
 */
// @ts-ignore
export function createScreenDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScreenDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScreenDto400Error(screenDto400Error: Partial<ScreenDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { screenDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface ScreenDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/screens/{id}
 */
export interface ScreensItemRequestBuilder extends BaseRequestBuilder<ScreensItemRequestBuilder> {
    /**
     * (Experimental) - Get a Screen by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ScreenDto>}
     * @throws {ScreenDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ScreenDto | undefined>;
    /**
     * (Experimental) - Get a Screen by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScreenDto400Error(writer: SerializationWriter, screenDto400Error: Partial<ScreenDto400Error> | undefined | null = {}) : void {
    if (screenDto400Error) {
        writer.writeStringValue("message", screenDto400Error.messageEscaped);
        writer.writeAdditionalData(screenDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const ScreensItemRequestBuilderUriTemplate = "{+baseurl}/v1/screens/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ScreensItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ScreensItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createScreenDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createScreenDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
