/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createItemDtoFromDiscriminatorValue, serializeItemCreateOrUpdateDto, serializeItemDto, type ItemCreateOrUpdateDto, type ItemDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemDto400Error}
 */
// @ts-ignore
export function createItemDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItemDto400Error;
}
/**
 * Builds and executes requests for operations under /v1/items/create-or-update
 */
export interface CreateOrUpdateRequestBuilder extends BaseRequestBuilder<CreateOrUpdateRequestBuilder> {
    /**
     * Create or update a Item
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ItemDto>}
     * @throws {ItemDto400Error} error when the service returns a 400 status code
     */
     post(body: ItemCreateOrUpdateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ItemDto | undefined>;
    /**
     * Create or update a Item
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ItemCreateOrUpdateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemDto400Error(itemDto400Error: Partial<ItemDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { itemDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface ItemDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemDto400Error(writer: SerializationWriter, itemDto400Error: Partial<ItemDto400Error> | undefined | null = {}) : void {
    if (itemDto400Error) {
        writer.writeStringValue("message", itemDto400Error.messageEscaped);
        writer.writeAdditionalData(itemDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const CreateOrUpdateRequestBuilderUriTemplate = "{+baseurl}/v1/items/create-or-update";
/**
 * Metadata for all the requests in the request builder.
 */
export const CreateOrUpdateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CreateOrUpdateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createItemDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createItemDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeItemCreateOrUpdateDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
