/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTableDtoFromDiscriminatorValue, serializeTableDto, type TableDto } from '../../models/index.js';
// @ts-ignore
import { TablesItemRequestBuilderRequestsMetadata, type TablesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Tables400Error}
 */
// @ts-ignore
export function createTables400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTables400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TablesGetResponse}
 */
// @ts-ignore
export function createTablesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTablesGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTables400Error(tables400Error: Partial<Tables400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { tables400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTablesGetResponse(tablesGetResponse: Partial<TablesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { tablesGetResponse.data = n.getCollectionOfObjectValues<TableDto>(createTableDtoFromDiscriminatorValue); },
        "object": n => { tablesGetResponse.object = n.getEnumValue<TablesGetResponse_object>(TablesGetResponse_objectObject); },
        "totalElements": n => { tablesGetResponse.totalElements = n.getNumberValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTables400Error(writer: SerializationWriter, tables400Error: Partial<Tables400Error> | undefined | null = {}) : void {
    if (tables400Error) {
        writer.writeStringValue("message", tables400Error.messageEscaped);
        writer.writeAdditionalData(tables400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTablesGetResponse(writer: SerializationWriter, tablesGetResponse: Partial<TablesGetResponse> | undefined | null = {}) : void {
    if (tablesGetResponse) {
        writer.writeCollectionOfObjectValues<TableDto>("data", tablesGetResponse.data, serializeTableDto);
        writer.writeEnumValue<TablesGetResponse_object>("object", tablesGetResponse.object);
        writer.writeNumberValue("totalElements", tablesGetResponse.totalElements);
        writer.writeAdditionalData(tablesGetResponse.additionalData);
    }
}
export interface Tables400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface TablesGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: TableDto[] | null;
    /**
     * The object property
     */
    object?: TablesGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type TablesGetResponse_object = (typeof TablesGetResponse_objectObject)[keyof typeof TablesGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/tables
 */
export interface TablesRequestBuilder extends BaseRequestBuilder<TablesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.tables.item collection
     * @param id Unique identifier of the item
     * @returns {TablesItemRequestBuilder}
     */
     byId(id: string) : TablesItemRequestBuilder;
    /**
     * Get a list of Table
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TablesGetResponse>}
     * @throws {Tables400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<TablesRequestBuilderGetQueryParameters> | undefined) : Promise<TablesGetResponse | undefined>;
    /**
     * Get a list of Table
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TablesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Table
 */
export interface TablesRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
}
/**
 * Uri template for the request builder.
 */
export const TablesRequestBuilderUriTemplate = "{+baseurl}/v1/tables{?page*,size*}";
export const TablesGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TablesRequestBuilderNavigationMetadata: Record<Exclude<keyof TablesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: TablesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TablesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TablesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTables400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTablesGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
