/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createItemDtoFromDiscriminatorValue, serializeItemDto, serializeItemFindDTO, type ItemDto, type ItemFindDTO } from '../../../../../../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithLevel400Error}
 */
// @ts-ignore
export function createWithLevel400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithLevel400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithLevelPostResponse}
 */
// @ts-ignore
export function createWithLevelPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithLevelPostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithLevel400Error(withLevel400Error: Partial<WithLevel400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { withLevel400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithLevelPostResponse(withLevelPostResponse: Partial<WithLevelPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { withLevelPostResponse.data = n.getCollectionOfObjectValues<ItemDto>(createItemDtoFromDiscriminatorValue); },
        "object": n => { withLevelPostResponse.object = n.getEnumValue<WithLevelPostResponse_object>(WithLevelPostResponse_objectObject); },
        "totalElements": n => { withLevelPostResponse.totalElements = n.getNumberValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithLevel400Error(writer: SerializationWriter, withLevel400Error: Partial<WithLevel400Error> | undefined | null = {}) : void {
    if (withLevel400Error) {
        writer.writeStringValue("message", withLevel400Error.messageEscaped);
        writer.writeAdditionalData(withLevel400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithLevelPostResponse(writer: SerializationWriter, withLevelPostResponse: Partial<WithLevelPostResponse> | undefined | null = {}) : void {
    if (withLevelPostResponse) {
        writer.writeCollectionOfObjectValues<ItemDto>("data", withLevelPostResponse.data, serializeItemDto);
        writer.writeEnumValue<WithLevelPostResponse_object>("object", withLevelPostResponse.object);
        writer.writeNumberValue("totalElements", withLevelPostResponse.totalElements);
        writer.writeAdditionalData(withLevelPostResponse.additionalData);
    }
}
export interface WithLevel400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/items/find/table/{tableId}/partition/{partitionId}/level/{levelId}
 */
export interface WithLevelItemRequestBuilder extends BaseRequestBuilder<WithLevelItemRequestBuilder> {
    /**
     * Find a list of Item
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WithLevelPostResponse>}
     * @throws {WithLevel400Error} error when the service returns a 400 status code
     * @deprecated 
     */
     post(body: ItemFindDTO, requestConfiguration?: RequestConfiguration<WithLevelItemRequestBuilderPostQueryParameters> | undefined) : Promise<WithLevelPostResponse | undefined>;
    /**
     * Find a list of Item
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated 
     */
     toPostRequestInformation(body: ItemFindDTO, requestConfiguration?: RequestConfiguration<WithLevelItemRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find a list of Item
 */
export interface WithLevelItemRequestBuilderPostQueryParameters {
    page?: number;
    size?: number;
}
export interface WithLevelPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: ItemDto[] | null;
    /**
     * The object property
     */
    object?: WithLevelPostResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type WithLevelPostResponse_object = (typeof WithLevelPostResponse_objectObject)[keyof typeof WithLevelPostResponse_objectObject];
/**
 * Uri template for the request builder.
 */
export const WithLevelItemRequestBuilderUriTemplate = "{+baseurl}/v1/items/find/table/{tableId}/partition/{partitionId}/level/{levelId}{?page*,size*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithLevelItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithLevelItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createWithLevel400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWithLevelPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeItemFindDTO,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
export const WithLevelPostResponse_objectObject = {
    List: "list",
} as const;
/* tslint:enable */
/* eslint-enable */
