/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFileDtoFromDiscriminatorValue, serializeFileDto, serializeFileUploadDto, type FileDto, type FileUploadDto } from '../../../models/index.js';
// @ts-ignore
import { FilesItemRequestBuilderRequestsMetadata, type FilesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FileDto413Error}
 */
// @ts-ignore
export function createFileDto413ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFileDto413Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Files400Error}
 */
// @ts-ignore
export function createFiles400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFiles400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FilesGetResponse}
 */
// @ts-ignore
export function createFilesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFilesGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFileDto413Error(fileDto413Error: Partial<FileDto413Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { fileDto413Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFiles400Error(files400Error: Partial<Files400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { files400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFilesGetResponse(filesGetResponse: Partial<FilesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { filesGetResponse.data = n.getCollectionOfObjectValues<FileDto>(createFileDtoFromDiscriminatorValue); },
        "object": n => { filesGetResponse.object = n.getEnumValue<FilesGetResponse_object>(FilesGetResponse_objectObject); },
        "totalElements": n => { filesGetResponse.totalElements = n.getNumberValue(); },
    }
}
export interface FileDto413Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Files400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface FilesGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: FileDto[] | null;
    /**
     * The object property
     */
    object?: FilesGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type FilesGetResponse_object = (typeof FilesGetResponse_objectObject)[keyof typeof FilesGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/data_factory/files
 */
export interface FilesRequestBuilder extends BaseRequestBuilder<FilesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.data_factory.files.item collection
     * @param id Unique identifier of the item
     * @returns {FilesItemRequestBuilder}
     */
     byId(id: string) : FilesItemRequestBuilder;
    /**
     * Get a list of Data Factory File
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FilesGetResponse>}
     * @throws {Files400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<FilesRequestBuilderGetQueryParameters> | undefined) : Promise<FilesGetResponse | undefined>;
    /**
     * Post a file so it can be consume by a Data Factory job
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FileDto>}
     * @throws {FileDto413Error} error when the service returns a 413 status code
     */
     post(body: FileUploadDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FileDto | undefined>;
    /**
     * Get a list of Data Factory File
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<FilesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Post a file so it can be consume by a Data Factory job
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: FileUploadDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a list of Data Factory File
 */
export interface FilesRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFileDto413Error(writer: SerializationWriter, fileDto413Error: Partial<FileDto413Error> | undefined | null = {}) : void {
    if (fileDto413Error) {
        writer.writeStringValue("message", fileDto413Error.messageEscaped);
        writer.writeAdditionalData(fileDto413Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFiles400Error(writer: SerializationWriter, files400Error: Partial<Files400Error> | undefined | null = {}) : void {
    if (files400Error) {
        writer.writeStringValue("message", files400Error.messageEscaped);
        writer.writeAdditionalData(files400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFilesGetResponse(writer: SerializationWriter, filesGetResponse: Partial<FilesGetResponse> | undefined | null = {}) : void {
    if (filesGetResponse) {
        writer.writeCollectionOfObjectValues<FileDto>("data", filesGetResponse.data, serializeFileDto);
        writer.writeEnumValue<FilesGetResponse_object>("object", filesGetResponse.object);
        writer.writeNumberValue("totalElements", filesGetResponse.totalElements);
        writer.writeAdditionalData(filesGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const FilesRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/files{?page*,size*}";
export const FilesGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FilesRequestBuilderNavigationMetadata: Record<Exclude<keyof FilesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: FilesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const FilesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFiles400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFilesGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: FilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            413: createFileDto413ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFileDtoFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeFileUploadDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
