/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPartitionDtoFromDiscriminatorValue, type PartitionDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PartitionDto400Error}
 */
// @ts-ignore
export function createPartitionDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPartitionDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPartitionDto400Error(partitionDto400Error: Partial<PartitionDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { partitionDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface PartitionDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/partitions/{id}
 */
export interface PartitionsItemRequestBuilder extends BaseRequestBuilder<PartitionsItemRequestBuilder> {
    /**
     * Get a Partition by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PartitionDto>}
     * @throws {PartitionDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PartitionDto | undefined>;
    /**
     * Get a Partition by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePartitionDto400Error(writer: SerializationWriter, partitionDto400Error: Partial<PartitionDto400Error> | undefined | null = {}) : void {
    if (partitionDto400Error) {
        writer.writeStringValue("message", partitionDto400Error.messageEscaped);
        writer.writeAdditionalData(partitionDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const PartitionsItemRequestBuilderUriTemplate = "{+baseurl}/v1/partitions/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PartitionsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PartitionsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createPartitionDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPartitionDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
