/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMatrixFieldDtoFromDiscriminatorValue, serializeMatrixFieldDto, type MatrixFieldDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { Matrix_fieldsItemRequestBuilderRequestsMetadata, type Matrix_fieldsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Matrix_fields400Error}
 */
// @ts-ignore
export function createMatrix_fields400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMatrix_fields400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Matrix_fieldsGetResponse}
 */
// @ts-ignore
export function createMatrix_fieldsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMatrix_fieldsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMatrix_fields400Error(matrix_fields400Error: Partial<Matrix_fields400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { matrix_fields400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMatrix_fieldsGetResponse(matrix_fieldsGetResponse: Partial<Matrix_fieldsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { matrix_fieldsGetResponse.data = n.getCollectionOfObjectValues<MatrixFieldDto>(createMatrixFieldDtoFromDiscriminatorValue); },
        "object": n => { matrix_fieldsGetResponse.object = n.getEnumValue<Matrix_fieldsGetResponse_object>(Matrix_fieldsGetResponse_objectObject); },
        "totalElements": n => { matrix_fieldsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
export interface Matrix_fields400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Matrix_fieldsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: MatrixFieldDto[] | null;
    /**
     * The object property
     */
    object?: Matrix_fieldsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type Matrix_fieldsGetResponse_object = (typeof Matrix_fieldsGetResponse_objectObject)[keyof typeof Matrix_fieldsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/matrix_fields
 */
export interface Matrix_fieldsRequestBuilder extends BaseRequestBuilder<Matrix_fieldsRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.matrix_fields.item collection
     * @param id Unique identifier of the item
     * @returns {Matrix_fieldsItemRequestBuilder}
     */
     byId(id: string) : Matrix_fieldsItemRequestBuilder;
    /**
     * Get a list of MatrixField
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Matrix_fieldsGetResponse>}
     * @throws {Matrix_fields400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<Matrix_fieldsRequestBuilderGetQueryParameters> | undefined) : Promise<Matrix_fieldsGetResponse | undefined>;
    /**
     * Get a list of MatrixField
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Matrix_fieldsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of MatrixField
 */
export interface Matrix_fieldsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
    tableId?: string;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMatrix_fields400Error(writer: SerializationWriter, matrix_fields400Error: Partial<Matrix_fields400Error> | undefined | null = {}) : void {
    if (matrix_fields400Error) {
        writer.writeStringValue("message", matrix_fields400Error.messageEscaped);
        writer.writeAdditionalData(matrix_fields400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMatrix_fieldsGetResponse(writer: SerializationWriter, matrix_fieldsGetResponse: Partial<Matrix_fieldsGetResponse> | undefined | null = {}) : void {
    if (matrix_fieldsGetResponse) {
        writer.writeCollectionOfObjectValues<MatrixFieldDto>("data", matrix_fieldsGetResponse.data, serializeMatrixFieldDto);
        writer.writeEnumValue<Matrix_fieldsGetResponse_object>("object", matrix_fieldsGetResponse.object);
        writer.writeNumberValue("totalElements", matrix_fieldsGetResponse.totalElements);
        writer.writeAdditionalData(matrix_fieldsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Matrix_fieldsRequestBuilderUriTemplate = "{+baseurl}/v1/matrix_fields?tableId={tableId}{&page*,size*,sort*,sortOrder*}";
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
export const Matrix_fieldsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Matrix_fieldsRequestBuilderNavigationMetadata: Record<Exclude<keyof Matrix_fieldsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: Matrix_fieldsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Matrix_fieldsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Matrix_fieldsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMatrix_fields400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMatrix_fieldsGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
