/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSuggestionDtoFromDiscriminatorValue, type SuggestionDto } from '../../../models/index.js';
// @ts-ignore
import { ApplyRequestBuilderRequestsMetadata, type ApplyRequestBuilder } from './apply/index.js';
// @ts-ignore
import { ApplyAllRequestBuilderRequestsMetadata, type ApplyAllRequestBuilder } from './applyAll/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SuggestionDto400Error}
 */
// @ts-ignore
export function createSuggestionDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSuggestionDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSuggestionDto400Error(suggestionDto400Error: Partial<SuggestionDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { suggestionDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSuggestionDto400Error(writer: SerializationWriter, suggestionDto400Error: Partial<SuggestionDto400Error> | undefined | null = {}) : void {
    if (suggestionDto400Error) {
        writer.writeStringValue("message", suggestionDto400Error.messageEscaped);
        writer.writeAdditionalData(suggestionDto400Error.additionalData);
    }
}
export interface SuggestionDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/suggestions/{id}
 */
export interface SuggestionsItemRequestBuilder extends BaseRequestBuilder<SuggestionsItemRequestBuilder> {
    /**
     * The apply property
     */
    get apply(): ApplyRequestBuilder;
    /**
     * The applyAll property
     */
    get applyAll(): ApplyAllRequestBuilder;
    /**
     * Get a Suggestion by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SuggestionDto>}
     * @throws {SuggestionDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SuggestionDto | undefined>;
    /**
     * Get a Suggestion by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SuggestionsItemRequestBuilderUriTemplate = "{+baseurl}/v1/suggestions/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SuggestionsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof SuggestionsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    apply: {
        requestsMetadata: ApplyRequestBuilderRequestsMetadata,
    },
    applyAll: {
        requestsMetadata: ApplyAllRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SuggestionsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SuggestionsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createSuggestionDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSuggestionDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
