/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createVariableDtoFromDiscriminatorValue, serializeUpdateVariableDto, serializeVariableDto, type UpdateVariableDto, type VariableDto } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {VariableDto400Error}
 */
// @ts-ignore
export function createVariableDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVariableDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVariableDto400Error(variableDto400Error: Partial<VariableDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { variableDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVariableDto400Error(writer: SerializationWriter, variableDto400Error: Partial<VariableDto400Error> | undefined | null = {}) : void {
    if (variableDto400Error) {
        writer.writeStringValue("message", variableDto400Error.messageEscaped);
        writer.writeAdditionalData(variableDto400Error.additionalData);
    }
}
export interface VariableDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/data_factory/variables/{id}
 */
export interface VariablesItemRequestBuilder extends BaseRequestBuilder<VariablesItemRequestBuilder> {
    /**
     * Get a Variable by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VariableDto>}
     * @throws {VariableDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VariableDto | undefined>;
    /**
     * Update a Variable
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VariableDto>}
     * @throws {VariableDto400Error} error when the service returns a 400 status code
     */
     put(body: UpdateVariableDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VariableDto | undefined>;
    /**
     * Get a Variable by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update a Variable
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateVariableDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VariablesItemRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/variables/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const VariablesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VariablesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createVariableDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createVariableDtoFromDiscriminatorValue,
    },
    put: {
        uriTemplate: VariablesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createVariableDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createVariableDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateVariableDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
