/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMatrixFieldDtoFromDiscriminatorValue, type MatrixFieldDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MatrixFieldDto400Error}
 */
// @ts-ignore
export function createMatrixFieldDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMatrixFieldDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMatrixFieldDto400Error(matrixFieldDto400Error: Partial<MatrixFieldDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { matrixFieldDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Builds and executes requests for operations under /v1/matrix_fields/{id}
 */
export interface Matrix_fieldsItemRequestBuilder extends BaseRequestBuilder<Matrix_fieldsItemRequestBuilder> {
    /**
     * Get a MatrixField by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MatrixFieldDto>}
     * @throws {MatrixFieldDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MatrixFieldDto | undefined>;
    /**
     * Get a MatrixField by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface MatrixFieldDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMatrixFieldDto400Error(writer: SerializationWriter, matrixFieldDto400Error: Partial<MatrixFieldDto400Error> | undefined | null = {}) : void {
    if (matrixFieldDto400Error) {
        writer.writeStringValue("message", matrixFieldDto400Error.messageEscaped);
        writer.writeAdditionalData(matrixFieldDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Matrix_fieldsItemRequestBuilderUriTemplate = "{+baseurl}/v1/matrix_fields/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const Matrix_fieldsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Matrix_fieldsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMatrixFieldDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMatrixFieldDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
