/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHighOrderQueryDTOFromDiscriminatorValue, createLevelDtoFromDiscriminatorValue, createLowOrderQueryDTOFromDiscriminatorValue, deserializeIntoHighOrderQueryDTO, deserializeIntoLowOrderQueryDTO, serializeHighOrderQueryDTO, serializeLevelDto, serializeLowOrderQueryDTO, type HighOrderQueryDTO, type LevelDto, type LowOrderQueryDTO } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Find400Error}
 */
// @ts-ignore
export function createFind400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFind400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FindPostResponse}
 */
// @ts-ignore
export function createFindPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFindPostResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HighOrderQueryDTO | LowOrderQueryDTO}
 */
// @ts-ignore
export function createQueryDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    const mappingValueNode = parseNode?.getChildNode("type");
    if (mappingValueNode) {
        const mappingValue = mappingValueNode.getStringValue();
        if (mappingValue) {
            switch (mappingValue) {
                case "and":
                    return deserializeIntoHighOrderQueryDTO;
                case "eq":
                    return deserializeIntoLowOrderQueryDTO;
                case "false":
                    return deserializeIntoLowOrderQueryDTO;
                case "greater":
                    return deserializeIntoLowOrderQueryDTO;
                case "greaterOrEqual":
                    return deserializeIntoLowOrderQueryDTO;
                case "in":
                    return deserializeIntoLowOrderQueryDTO;
                case "isNull":
                    return deserializeIntoLowOrderQueryDTO;
                case "localizedSearch":
                    return deserializeIntoLowOrderQueryDTO;
                case "lower":
                    return deserializeIntoLowOrderQueryDTO;
                case "lowerOrEqual":
                    return deserializeIntoLowOrderQueryDTO;
                case "notIn":
                    return deserializeIntoLowOrderQueryDTO;
                case "or":
                    return deserializeIntoHighOrderQueryDTO;
                case "search":
                    return deserializeIntoLowOrderQueryDTO;
                case "true":
                    return deserializeIntoLowOrderQueryDTO;
            }
        }
    }
    return deserializeIntoQueryDTO;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFind400Error(find400Error: Partial<Find400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { find400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFindPostResponse(findPostResponse: Partial<FindPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { findPostResponse.data = n.getCollectionOfObjectValues<LevelDto>(createLevelDtoFromDiscriminatorValue); },
        "object": n => { findPostResponse.object = n.getEnumValue<FindPostResponse_object>(FindPostResponse_objectObject); },
        "totalElements": n => { findPostResponse.totalElements = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryDTO(queryDTO: Partial<HighOrderQueryDTO | LowOrderQueryDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoHighOrderQueryDTO(queryDTO as HighOrderQueryDTO),
        ...deserializeIntoLowOrderQueryDTO(queryDTO as LowOrderQueryDTO),
    }
}
export interface Find400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface FindPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: LevelDto[] | null;
    /**
     * The object property
     */
    object?: FindPostResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type FindPostResponse_object = (typeof FindPostResponse_objectObject)[keyof typeof FindPostResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/levels/find
 */
export interface FindRequestBuilder extends BaseRequestBuilder<FindRequestBuilder> {
    /**
     * Find a list of Level
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindPostResponse>}
     * @throws {Find400Error} error when the service returns a 400 status code
     */
     post(body: HighOrderQueryDTO | LowOrderQueryDTO, requestConfiguration?: RequestConfiguration<FindRequestBuilderPostQueryParameters> | undefined) : Promise<FindPostResponse | undefined>;
    /**
     * Find a list of Level
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HighOrderQueryDTO | LowOrderQueryDTO, requestConfiguration?: RequestConfiguration<FindRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find a list of Level
 */
export interface FindRequestBuilderPostQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: PostSortOrderQueryParameterType;
    tableId?: string;
}
export type PostSortOrderQueryParameterType = (typeof PostSortOrderQueryParameterTypeObject)[keyof typeof PostSortOrderQueryParameterTypeObject];
export type QueryDTO = HighOrderQueryDTO | LowOrderQueryDTO;
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFind400Error(writer: SerializationWriter, find400Error: Partial<Find400Error> | undefined | null = {}) : void {
    if (find400Error) {
        writer.writeStringValue("message", find400Error.messageEscaped);
        writer.writeAdditionalData(find400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFindPostResponse(writer: SerializationWriter, findPostResponse: Partial<FindPostResponse> | undefined | null = {}) : void {
    if (findPostResponse) {
        writer.writeCollectionOfObjectValues<LevelDto>("data", findPostResponse.data, serializeLevelDto);
        writer.writeEnumValue<FindPostResponse_object>("object", findPostResponse.object);
        writer.writeNumberValue("totalElements", findPostResponse.totalElements);
        writer.writeAdditionalData(findPostResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryDTO(writer: SerializationWriter, queryDTO: Partial<HighOrderQueryDTO | LowOrderQueryDTO> | undefined | null = {}) : void {
    if (queryDTO === undefined || queryDTO === null) return;
    switch (queryDTO.type) {
        case "and":
            serializeHighOrderQueryDTO(writer, queryDTO as HighOrderQueryDTO);
            break;
        case "eq":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "false":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "greater":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "greaterOrEqual":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "in":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "isNull":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "localizedSearch":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "lower":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "lowerOrEqual":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "notIn":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "or":
            serializeHighOrderQueryDTO(writer, queryDTO as HighOrderQueryDTO);
            break;
        case "search":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
        case "true":
            serializeLowOrderQueryDTO(writer, queryDTO as LowOrderQueryDTO);
            break;
    }
}
/**
 * Uri template for the request builder.
 */
export const FindRequestBuilderUriTemplate = "{+baseurl}/v1/levels/find?tableId={tableId}{&page*,size*,sort*,sortOrder*}";
export const FindPostResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the requests in the request builder.
 */
export const FindRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: FindRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFind400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryDTO,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
export const PostSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
/* tslint:enable */
/* eslint-enable */
