/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTableItemRequestBuilder, WithTableItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/items/find/table
 */
export interface TableRequestBuilder extends BaseRequestBuilder<TableRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.items.find.table.item collection
     * @param tableId Unique identifier of the item
     * @returns {WithTableItemRequestBuilder}
     */
     byTableId(tableId: string) : WithTableItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TableRequestBuilderUriTemplate = "{+baseurl}/v1/items/find/table";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TableRequestBuilderNavigationMetadata: Record<Exclude<keyof TableRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTableId: {
        navigationMetadata: WithTableItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["tableId"],
    },
};
/* tslint:enable */
/* eslint-enable */
