/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobDtoFromDiscriminatorValue, serializeCreateJobDto, serializeJobDto, type CreateJobDto, type JobDto } from '../../../models/index.js';
// @ts-ignore
import { JobsItemRequestBuilderNavigationMetadata, JobsItemRequestBuilderRequestsMetadata, type JobsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobDto400Error}
 */
// @ts-ignore
export function createJobDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Jobs400Error}
 */
// @ts-ignore
export function createJobs400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobs400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobsGetResponse}
 */
// @ts-ignore
export function createJobsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobDto400Error(jobDto400Error: Partial<JobDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { jobDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobs400Error(jobs400Error: Partial<Jobs400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { jobs400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobsGetResponse(jobsGetResponse: Partial<JobsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { jobsGetResponse.data = n.getCollectionOfObjectValues<JobDto>(createJobDtoFromDiscriminatorValue); },
        "object": n => { jobsGetResponse.object = n.getEnumValue<JobsGetResponse_object>(JobsGetResponse_objectObject); },
        "totalElements": n => { jobsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export interface JobDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Jobs400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface JobsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: JobDto[] | null;
    /**
     * The object property
     */
    object?: JobsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type JobsGetResponse_object = (typeof JobsGetResponse_objectObject)[keyof typeof JobsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/data_factory/jobs
 */
export interface JobsRequestBuilder extends BaseRequestBuilder<JobsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.data_factory.jobs.item collection
     * @param id Unique identifier of the item
     * @returns {JobsItemRequestBuilder}
     */
     byId(id: string) : JobsItemRequestBuilder;
    /**
     * Get a list of Job
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobsGetResponse>}
     * @throws {Jobs400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<JobsRequestBuilderGetQueryParameters> | undefined) : Promise<JobsGetResponse | undefined>;
    /**
     * Create a Job
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobDto>}
     * @throws {JobDto400Error} error when the service returns a 400 status code
     */
     post(body: CreateJobDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobDto | undefined>;
    /**
     * Get a list of Job
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<JobsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a Job
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateJobDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a list of Job
 */
export interface JobsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobDto400Error(writer: SerializationWriter, jobDto400Error: Partial<JobDto400Error> | undefined | null = {}) : void {
    if (jobDto400Error) {
        writer.writeStringValue("message", jobDto400Error.messageEscaped);
        writer.writeAdditionalData(jobDto400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobs400Error(writer: SerializationWriter, jobs400Error: Partial<Jobs400Error> | undefined | null = {}) : void {
    if (jobs400Error) {
        writer.writeStringValue("message", jobs400Error.messageEscaped);
        writer.writeAdditionalData(jobs400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobsGetResponse(writer: SerializationWriter, jobsGetResponse: Partial<JobsGetResponse> | undefined | null = {}) : void {
    if (jobsGetResponse) {
        writer.writeCollectionOfObjectValues<JobDto>("data", jobsGetResponse.data, serializeJobDto);
        writer.writeEnumValue<JobsGetResponse_object>("object", jobsGetResponse.object);
        writer.writeNumberValue("totalElements", jobsGetResponse.totalElements);
        writer.writeAdditionalData(jobsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const JobsRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/jobs{?page*,size*}";
export const JobsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JobsRequestBuilderNavigationMetadata: Record<Exclude<keyof JobsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: JobsItemRequestBuilderRequestsMetadata,
        navigationMetadata: JobsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const JobsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: JobsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createJobs400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobsGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: JobsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createJobDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateJobDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
