/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FilesRequestBuilderNavigationMetadata, FilesRequestBuilderRequestsMetadata, type FilesRequestBuilder } from './files/index.js';
// @ts-ignore
import { Job_executionsRequestBuilderNavigationMetadata, Job_executionsRequestBuilderRequestsMetadata, type Job_executionsRequestBuilder } from './job_executions/index.js';
// @ts-ignore
import { JobsRequestBuilderNavigationMetadata, JobsRequestBuilderRequestsMetadata, type JobsRequestBuilder } from './jobs/index.js';
// @ts-ignore
import { Task_executionsRequestBuilderNavigationMetadata, type Task_executionsRequestBuilder } from './task_executions/index.js';
// @ts-ignore
import { TasksRequestBuilderNavigationMetadata, TasksRequestBuilderRequestsMetadata, type TasksRequestBuilder } from './tasks/index.js';
// @ts-ignore
import { type VariablesRequestBuilder, VariablesRequestBuilderNavigationMetadata, VariablesRequestBuilderRequestsMetadata } from './variables/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/data_factory
 */
export interface Data_factoryRequestBuilder extends BaseRequestBuilder<Data_factoryRequestBuilder> {
    /**
     * The files property
     */
    get files(): FilesRequestBuilder;
    /**
     * The job_executions property
     */
    get job_executions(): Job_executionsRequestBuilder;
    /**
     * The jobs property
     */
    get jobs(): JobsRequestBuilder;
    /**
     * The task_executions property
     */
    get task_executions(): Task_executionsRequestBuilder;
    /**
     * The tasks property
     */
    get tasks(): TasksRequestBuilder;
    /**
     * The variables property
     */
    get variables(): VariablesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const Data_factoryRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Data_factoryRequestBuilderNavigationMetadata: Record<Exclude<keyof Data_factoryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    files: {
        requestsMetadata: FilesRequestBuilderRequestsMetadata,
        navigationMetadata: FilesRequestBuilderNavigationMetadata,
    },
    jobs: {
        requestsMetadata: JobsRequestBuilderRequestsMetadata,
        navigationMetadata: JobsRequestBuilderNavigationMetadata,
    },
    job_executions: {
        requestsMetadata: Job_executionsRequestBuilderRequestsMetadata,
        navigationMetadata: Job_executionsRequestBuilderNavigationMetadata,
    },
    tasks: {
        requestsMetadata: TasksRequestBuilderRequestsMetadata,
        navigationMetadata: TasksRequestBuilderNavigationMetadata,
    },
    task_executions: {
        navigationMetadata: Task_executionsRequestBuilderNavigationMetadata,
    },
    variables: {
        requestsMetadata: VariablesRequestBuilderRequestsMetadata,
        navigationMetadata: VariablesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
