/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createScreenColumnDtoFromDiscriminatorValue, serializeScreenColumnDto, type ScreenColumnDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { Screen_columnsItemRequestBuilderRequestsMetadata, type Screen_columnsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Screen_columns400Error}
 */
// @ts-ignore
export function createScreen_columns400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScreen_columns400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Screen_columnsGetResponse}
 */
// @ts-ignore
export function createScreen_columnsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScreen_columnsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScreen_columns400Error(screen_columns400Error: Partial<Screen_columns400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { screen_columns400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScreen_columnsGetResponse(screen_columnsGetResponse: Partial<Screen_columnsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { screen_columnsGetResponse.data = n.getCollectionOfObjectValues<ScreenColumnDto>(createScreenColumnDtoFromDiscriminatorValue); },
        "object": n => { screen_columnsGetResponse.object = n.getEnumValue<Screen_columnsGetResponse_object>(Screen_columnsGetResponse_objectObject); },
        "totalElements": n => { screen_columnsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
export interface Screen_columns400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Screen_columnsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: ScreenColumnDto[] | null;
    /**
     * The object property
     */
    object?: Screen_columnsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type Screen_columnsGetResponse_object = (typeof Screen_columnsGetResponse_objectObject)[keyof typeof Screen_columnsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/screen_columns
 */
export interface Screen_columnsRequestBuilder extends BaseRequestBuilder<Screen_columnsRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.screen_columns.item collection
     * @param id Unique identifier of the item
     * @returns {Screen_columnsItemRequestBuilder}
     */
     byId(id: string) : Screen_columnsItemRequestBuilder;
    /**
     * (Experimental) - Get a list of Screen Column
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Screen_columnsGetResponse>}
     * @throws {Screen_columns400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<Screen_columnsRequestBuilderGetQueryParameters> | undefined) : Promise<Screen_columnsGetResponse | undefined>;
    /**
     * (Experimental) - Get a list of Screen Column
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Screen_columnsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * (Experimental) - Get a list of Screen Column
 */
export interface Screen_columnsRequestBuilderGetQueryParameters {
    page?: number;
    screenSectionId?: string;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScreen_columns400Error(writer: SerializationWriter, screen_columns400Error: Partial<Screen_columns400Error> | undefined | null = {}) : void {
    if (screen_columns400Error) {
        writer.writeStringValue("message", screen_columns400Error.messageEscaped);
        writer.writeAdditionalData(screen_columns400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScreen_columnsGetResponse(writer: SerializationWriter, screen_columnsGetResponse: Partial<Screen_columnsGetResponse> | undefined | null = {}) : void {
    if (screen_columnsGetResponse) {
        writer.writeCollectionOfObjectValues<ScreenColumnDto>("data", screen_columnsGetResponse.data, serializeScreenColumnDto);
        writer.writeEnumValue<Screen_columnsGetResponse_object>("object", screen_columnsGetResponse.object);
        writer.writeNumberValue("totalElements", screen_columnsGetResponse.totalElements);
        writer.writeAdditionalData(screen_columnsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Screen_columnsRequestBuilderUriTemplate = "{+baseurl}/v1/screen_columns?screenSectionId={screenSectionId}{&page*,size*,sort*,sortOrder*}";
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
export const Screen_columnsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Screen_columnsRequestBuilderNavigationMetadata: Record<Exclude<keyof Screen_columnsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: Screen_columnsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Screen_columnsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Screen_columnsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createScreen_columns400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createScreen_columnsGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
