/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createScreenSectionDtoFromDiscriminatorValue, type ScreenSectionDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ScreenSectionDto400Error}
 */
// @ts-ignore
export function createScreenSectionDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScreenSectionDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScreenSectionDto400Error(screenSectionDto400Error: Partial<ScreenSectionDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { screenSectionDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Builds and executes requests for operations under /v1/screen_sections/{id}
 */
export interface Screen_sectionsItemRequestBuilder extends BaseRequestBuilder<Screen_sectionsItemRequestBuilder> {
    /**
     * (Experimental) - Get a Screen Section by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ScreenSectionDto>}
     * @throws {ScreenSectionDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ScreenSectionDto | undefined>;
    /**
     * (Experimental) - Get a Screen Section by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface ScreenSectionDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScreenSectionDto400Error(writer: SerializationWriter, screenSectionDto400Error: Partial<ScreenSectionDto400Error> | undefined | null = {}) : void {
    if (screenSectionDto400Error) {
        writer.writeStringValue("message", screenSectionDto400Error.messageEscaped);
        writer.writeAdditionalData(screenSectionDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Screen_sectionsItemRequestBuilderUriTemplate = "{+baseurl}/v1/screen_sections/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const Screen_sectionsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Screen_sectionsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createScreenSectionDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createScreenSectionDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
