/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLevelDtoFromDiscriminatorValue, serializeLevelDto, type LevelDto } from '../../models/index.js';
// @ts-ignore
import { LevelsItemRequestBuilderRequestsMetadata, type LevelsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Levels400Error}
 */
// @ts-ignore
export function createLevels400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLevels400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LevelsGetResponse}
 */
// @ts-ignore
export function createLevelsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLevelsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLevels400Error(levels400Error: Partial<Levels400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { levels400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLevelsGetResponse(levelsGetResponse: Partial<LevelsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { levelsGetResponse.data = n.getCollectionOfObjectValues<LevelDto>(createLevelDtoFromDiscriminatorValue); },
        "object": n => { levelsGetResponse.object = n.getEnumValue<LevelsGetResponse_object>(LevelsGetResponse_objectObject); },
        "totalElements": n => { levelsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export interface Levels400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface LevelsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: LevelDto[] | null;
    /**
     * The object property
     */
    object?: LevelsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type LevelsGetResponse_object = (typeof LevelsGetResponse_objectObject)[keyof typeof LevelsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/levels
 */
export interface LevelsRequestBuilder extends BaseRequestBuilder<LevelsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.levels.item collection
     * @param id Unique identifier of the item
     * @returns {LevelsItemRequestBuilder}
     */
     byId(id: string) : LevelsItemRequestBuilder;
    /**
     * Get a list of Level
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LevelsGetResponse>}
     * @throws {Levels400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<LevelsRequestBuilderGetQueryParameters> | undefined) : Promise<LevelsGetResponse | undefined>;
    /**
     * Get a list of Level
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<LevelsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Level
 */
export interface LevelsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLevels400Error(writer: SerializationWriter, levels400Error: Partial<Levels400Error> | undefined | null = {}) : void {
    if (levels400Error) {
        writer.writeStringValue("message", levels400Error.messageEscaped);
        writer.writeAdditionalData(levels400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLevelsGetResponse(writer: SerializationWriter, levelsGetResponse: Partial<LevelsGetResponse> | undefined | null = {}) : void {
    if (levelsGetResponse) {
        writer.writeCollectionOfObjectValues<LevelDto>("data", levelsGetResponse.data, serializeLevelDto);
        writer.writeEnumValue<LevelsGetResponse_object>("object", levelsGetResponse.object);
        writer.writeNumberValue("totalElements", levelsGetResponse.totalElements);
        writer.writeAdditionalData(levelsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const LevelsRequestBuilderUriTemplate = "{+baseurl}/v1/levels{?page*,size*}";
export const LevelsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LevelsRequestBuilderNavigationMetadata: Record<Exclude<keyof LevelsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: LevelsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LevelsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LevelsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createLevels400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLevelsGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
