/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCommentThreadSubscriberDtoFromDiscriminatorValue, serializeCommentThreadSubscriberDto, type CommentThreadSubscriberDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { Comment_thread_subscribersItemRequestBuilderRequestsMetadata, type Comment_thread_subscribersItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface Comment_thread_subscribers400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Comment_thread_subscribersGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: CommentThreadSubscriberDto[] | null;
    /**
     * The object property
     */
    object?: Comment_thread_subscribersGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type Comment_thread_subscribersGetResponse_object = (typeof Comment_thread_subscribersGetResponse_objectObject)[keyof typeof Comment_thread_subscribersGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/comment_thread_subscribers
 */
export interface Comment_thread_subscribersRequestBuilder extends BaseRequestBuilder<Comment_thread_subscribersRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.comment_thread_subscribers.item collection
     * @param id Unique identifier of the item
     * @returns {Comment_thread_subscribersItemRequestBuilder}
     */
     byId(id: string) : Comment_thread_subscribersItemRequestBuilder;
    /**
     * Get a list of Comment Thread Subscriber
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Comment_thread_subscribersGetResponse>}
     * @throws {Comment_thread_subscribers400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<Comment_thread_subscribersRequestBuilderGetQueryParameters> | undefined) : Promise<Comment_thread_subscribersGetResponse | undefined>;
    /**
     * Get a list of Comment Thread Subscriber
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Comment_thread_subscribersRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Comment Thread Subscriber
 */
export interface Comment_thread_subscribersRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Comment_thread_subscribers400Error}
 */
// @ts-ignore
export function createComment_thread_subscribers400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoComment_thread_subscribers400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Comment_thread_subscribersGetResponse}
 */
// @ts-ignore
export function createComment_thread_subscribersGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoComment_thread_subscribersGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoComment_thread_subscribers400Error(comment_thread_subscribers400Error: Partial<Comment_thread_subscribers400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { comment_thread_subscribers400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoComment_thread_subscribersGetResponse(comment_thread_subscribersGetResponse: Partial<Comment_thread_subscribersGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { comment_thread_subscribersGetResponse.data = n.getCollectionOfObjectValues<CommentThreadSubscriberDto>(createCommentThreadSubscriberDtoFromDiscriminatorValue); },
        "object": n => { comment_thread_subscribersGetResponse.object = n.getEnumValue<Comment_thread_subscribersGetResponse_object>(Comment_thread_subscribersGetResponse_objectObject); },
        "totalElements": n => { comment_thread_subscribersGetResponse.totalElements = n.getNumberValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeComment_thread_subscribers400Error(writer: SerializationWriter, comment_thread_subscribers400Error: Partial<Comment_thread_subscribers400Error> | undefined | null = {}) : void {
    if (comment_thread_subscribers400Error) {
        writer.writeStringValue("message", comment_thread_subscribers400Error.messageEscaped);
        writer.writeAdditionalData(comment_thread_subscribers400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeComment_thread_subscribersGetResponse(writer: SerializationWriter, comment_thread_subscribersGetResponse: Partial<Comment_thread_subscribersGetResponse> | undefined | null = {}) : void {
    if (comment_thread_subscribersGetResponse) {
        writer.writeCollectionOfObjectValues<CommentThreadSubscriberDto>("data", comment_thread_subscribersGetResponse.data, serializeCommentThreadSubscriberDto);
        writer.writeEnumValue<Comment_thread_subscribersGetResponse_object>("object", comment_thread_subscribersGetResponse.object);
        writer.writeNumberValue("totalElements", comment_thread_subscribersGetResponse.totalElements);
        writer.writeAdditionalData(comment_thread_subscribersGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Comment_thread_subscribersRequestBuilderUriTemplate = "{+baseurl}/v1/comment_thread_subscribers{?page*,size*}";
export const Comment_thread_subscribersGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Comment_thread_subscribersRequestBuilderNavigationMetadata: Record<Exclude<keyof Comment_thread_subscribersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: Comment_thread_subscribersItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Comment_thread_subscribersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Comment_thread_subscribersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createComment_thread_subscribers400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createComment_thread_subscribersGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
