/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PartitionRequestBuilderNavigationMetadata, type PartitionRequestBuilder } from './partition/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/items/find/table/{tableId}
 */
export interface WithTableItemRequestBuilder extends BaseRequestBuilder<WithTableItemRequestBuilder> {
    /**
     * The partition property
     */
    get partition(): PartitionRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTableItemRequestBuilderUriTemplate = "{+baseurl}/v1/items/find/table/{tableId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTableItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTableItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    partition: {
        navigationMetadata: PartitionRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
