/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPartitionDtoFromDiscriminatorValue, serializePartitionDto, type PartitionDto } from '../../models/index.js';
// @ts-ignore
import { PartitionsItemRequestBuilderRequestsMetadata, type PartitionsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Partitions400Error}
 */
// @ts-ignore
export function createPartitions400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPartitions400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PartitionsGetResponse}
 */
// @ts-ignore
export function createPartitionsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPartitionsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPartitions400Error(partitions400Error: Partial<Partitions400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { partitions400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPartitionsGetResponse(partitionsGetResponse: Partial<PartitionsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { partitionsGetResponse.data = n.getCollectionOfObjectValues<PartitionDto>(createPartitionDtoFromDiscriminatorValue); },
        "object": n => { partitionsGetResponse.object = n.getEnumValue<PartitionsGetResponse_object>(PartitionsGetResponse_objectObject); },
        "totalElements": n => { partitionsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export interface Partitions400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface PartitionsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: PartitionDto[] | null;
    /**
     * The object property
     */
    object?: PartitionsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type PartitionsGetResponse_object = (typeof PartitionsGetResponse_objectObject)[keyof typeof PartitionsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/partitions
 */
export interface PartitionsRequestBuilder extends BaseRequestBuilder<PartitionsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.partitions.item collection
     * @param id Unique identifier of the item
     * @returns {PartitionsItemRequestBuilder}
     */
     byId(id: string) : PartitionsItemRequestBuilder;
    /**
     * Get a list of Partition
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PartitionsGetResponse>}
     * @throws {Partitions400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<PartitionsRequestBuilderGetQueryParameters> | undefined) : Promise<PartitionsGetResponse | undefined>;
    /**
     * Get a list of Partition
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PartitionsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Partition
 */
export interface PartitionsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePartitions400Error(writer: SerializationWriter, partitions400Error: Partial<Partitions400Error> | undefined | null = {}) : void {
    if (partitions400Error) {
        writer.writeStringValue("message", partitions400Error.messageEscaped);
        writer.writeAdditionalData(partitions400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePartitionsGetResponse(writer: SerializationWriter, partitionsGetResponse: Partial<PartitionsGetResponse> | undefined | null = {}) : void {
    if (partitionsGetResponse) {
        writer.writeCollectionOfObjectValues<PartitionDto>("data", partitionsGetResponse.data, serializePartitionDto);
        writer.writeEnumValue<PartitionsGetResponse_object>("object", partitionsGetResponse.object);
        writer.writeNumberValue("totalElements", partitionsGetResponse.totalElements);
        writer.writeAdditionalData(partitionsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const PartitionsRequestBuilderUriTemplate = "{+baseurl}/v1/partitions{?page*,size*}";
export const PartitionsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PartitionsRequestBuilderNavigationMetadata: Record<Exclude<keyof PartitionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: PartitionsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PartitionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PartitionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createPartitions400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPartitionsGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
