/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskDtoFromDiscriminatorValue, serializeCreateTaskDto, serializeTaskDto, type CreateTaskDto, type TaskDto } from '../../../models/index.js';
// @ts-ignore
import { TasksItemRequestBuilderNavigationMetadata, TasksItemRequestBuilderRequestsMetadata, type TasksItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TaskDto400Error}
 */
// @ts-ignore
export function createTaskDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTaskDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Tasks400Error}
 */
// @ts-ignore
export function createTasks400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTasks400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TasksGetResponse}
 */
// @ts-ignore
export function createTasksGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTasksGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTaskDto400Error(taskDto400Error: Partial<TaskDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { taskDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTasks400Error(tasks400Error: Partial<Tasks400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { tasks400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTasksGetResponse(tasksGetResponse: Partial<TasksGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { tasksGetResponse.data = n.getCollectionOfObjectValues<TaskDto>(createTaskDtoFromDiscriminatorValue); },
        "object": n => { tasksGetResponse.object = n.getEnumValue<TasksGetResponse_object>(TasksGetResponse_objectObject); },
        "totalElements": n => { tasksGetResponse.totalElements = n.getNumberValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTaskDto400Error(writer: SerializationWriter, taskDto400Error: Partial<TaskDto400Error> | undefined | null = {}) : void {
    if (taskDto400Error) {
        writer.writeStringValue("message", taskDto400Error.messageEscaped);
        writer.writeAdditionalData(taskDto400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTasks400Error(writer: SerializationWriter, tasks400Error: Partial<Tasks400Error> | undefined | null = {}) : void {
    if (tasks400Error) {
        writer.writeStringValue("message", tasks400Error.messageEscaped);
        writer.writeAdditionalData(tasks400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTasksGetResponse(writer: SerializationWriter, tasksGetResponse: Partial<TasksGetResponse> | undefined | null = {}) : void {
    if (tasksGetResponse) {
        writer.writeCollectionOfObjectValues<TaskDto>("data", tasksGetResponse.data, serializeTaskDto);
        writer.writeEnumValue<TasksGetResponse_object>("object", tasksGetResponse.object);
        writer.writeNumberValue("totalElements", tasksGetResponse.totalElements);
        writer.writeAdditionalData(tasksGetResponse.additionalData);
    }
}
export interface TaskDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Tasks400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface TasksGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: TaskDto[] | null;
    /**
     * The object property
     */
    object?: TasksGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type TasksGetResponse_object = (typeof TasksGetResponse_objectObject)[keyof typeof TasksGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/data_factory/tasks
 */
export interface TasksRequestBuilder extends BaseRequestBuilder<TasksRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.data_factory.tasks.item collection
     * @param id Unique identifier of the item
     * @returns {TasksItemRequestBuilder}
     */
     byId(id: string) : TasksItemRequestBuilder;
    /**
     * Get a list of Task
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TasksGetResponse>}
     * @throws {Tasks400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<TasksRequestBuilderGetQueryParameters> | undefined) : Promise<TasksGetResponse | undefined>;
    /**
     * Create a Task
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskDto>}
     * @throws {TaskDto400Error} error when the service returns a 400 status code
     */
     post(body: CreateTaskDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskDto | undefined>;
    /**
     * Get a list of Task
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TasksRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a Task
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateTaskDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a list of Task
 */
export interface TasksRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
}
/**
 * Uri template for the request builder.
 */
export const TasksRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/tasks{?page*,size*,sort*,sortOrder*}";
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
export const TasksGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TasksRequestBuilderNavigationMetadata: Record<Exclude<keyof TasksRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: TasksItemRequestBuilderRequestsMetadata,
        navigationMetadata: TasksItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TasksRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TasksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTasks400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTasksGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: TasksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTaskDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTaskDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateTaskDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
