/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createScreenDtoFromDiscriminatorValue, serializeScreenDto, type ScreenDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { ScreensItemRequestBuilderRequestsMetadata, type ScreensItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Screens400Error}
 */
// @ts-ignore
export function createScreens400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScreens400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ScreensGetResponse}
 */
// @ts-ignore
export function createScreensGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScreensGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScreens400Error(screens400Error: Partial<Screens400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { screens400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScreensGetResponse(screensGetResponse: Partial<ScreensGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { screensGetResponse.data = n.getCollectionOfObjectValues<ScreenDto>(createScreenDtoFromDiscriminatorValue); },
        "object": n => { screensGetResponse.object = n.getEnumValue<ScreensGetResponse_object>(ScreensGetResponse_objectObject); },
        "totalElements": n => { screensGetResponse.totalElements = n.getNumberValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
export interface Screens400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface ScreensGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: ScreenDto[] | null;
    /**
     * The object property
     */
    object?: ScreensGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type ScreensGetResponse_object = (typeof ScreensGetResponse_objectObject)[keyof typeof ScreensGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/screens
 */
export interface ScreensRequestBuilder extends BaseRequestBuilder<ScreensRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.screens.item collection
     * @param id Unique identifier of the item
     * @returns {ScreensItemRequestBuilder}
     */
     byId(id: string) : ScreensItemRequestBuilder;
    /**
     * (Experimental) - Get a list of Screen
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ScreensGetResponse>}
     * @throws {Screens400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<ScreensRequestBuilderGetQueryParameters> | undefined) : Promise<ScreensGetResponse | undefined>;
    /**
     * (Experimental) - Get a list of Screen
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ScreensRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * (Experimental) - Get a list of Screen
 */
export interface ScreensRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
    tableId?: string;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScreens400Error(writer: SerializationWriter, screens400Error: Partial<Screens400Error> | undefined | null = {}) : void {
    if (screens400Error) {
        writer.writeStringValue("message", screens400Error.messageEscaped);
        writer.writeAdditionalData(screens400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScreensGetResponse(writer: SerializationWriter, screensGetResponse: Partial<ScreensGetResponse> | undefined | null = {}) : void {
    if (screensGetResponse) {
        writer.writeCollectionOfObjectValues<ScreenDto>("data", screensGetResponse.data, serializeScreenDto);
        writer.writeEnumValue<ScreensGetResponse_object>("object", screensGetResponse.object);
        writer.writeNumberValue("totalElements", screensGetResponse.totalElements);
        writer.writeAdditionalData(screensGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const ScreensRequestBuilderUriTemplate = "{+baseurl}/v1/screens?tableId={tableId}{&page*,size*,sort*,sortOrder*}";
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
export const ScreensGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ScreensRequestBuilderNavigationMetadata: Record<Exclude<keyof ScreensRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ScreensItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ScreensRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ScreensRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createScreens400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createScreensGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
