/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithPartitionItemRequestBuilder, WithPartitionItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/items/find/table/{tableId}/partition
 */
export interface PartitionRequestBuilder extends BaseRequestBuilder<PartitionRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.items.find.table.item.partition.item collection
     * @param partitionId Unique identifier of the item
     * @returns {WithPartitionItemRequestBuilder}
     */
     byPartitionId(partitionId: string) : WithPartitionItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PartitionRequestBuilderUriTemplate = "{+baseurl}/v1/items/find/table/{tableId}/partition";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PartitionRequestBuilderNavigationMetadata: Record<Exclude<keyof PartitionRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byPartitionId: {
        navigationMetadata: WithPartitionItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["partitionId"],
    },
};
/* tslint:enable */
/* eslint-enable */
