/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFindItemHighOrderQueryDTOFromDiscriminatorValue, createFindItemLowOrderQueryDTOFromDiscriminatorValue, createItemDtoFromDiscriminatorValue, createLowOrderQueryDTOFromDiscriminatorValue, deserializeIntoFindItemHighOrderQueryDTO, deserializeIntoFindItemLowOrderQueryDTO, deserializeIntoLowOrderQueryDTO, serializeFindItemHighOrderQueryDTO, serializeFindItemLowOrderQueryDTO, serializeItemDto, serializeLowOrderQueryDTO, type FindItemHighOrderQueryDTO, type FindItemLowOrderQueryDTO, type ItemDto, type LowOrderQueryDTO } from '../../../models/index.js';
// @ts-ignore
import { TableRequestBuilderNavigationMetadata, type TableRequestBuilder } from './table/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Find400Error}
 */
// @ts-ignore
export function createFind400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFind400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FindItemHighOrderQueryDTO | FindItemLowOrderQueryDTO | LowOrderQueryDTO}
 */
// @ts-ignore
export function createFindItemQueryDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFindItemQueryDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FindPostResponse}
 */
// @ts-ignore
export function createFindPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFindPostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFind400Error(find400Error: Partial<Find400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { find400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFindItemQueryDto(findItemQueryDto: Partial<FindItemHighOrderQueryDTO | FindItemLowOrderQueryDTO | LowOrderQueryDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoFindItemHighOrderQueryDTO(findItemQueryDto as FindItemHighOrderQueryDTO),
        ...deserializeIntoFindItemLowOrderQueryDTO(findItemQueryDto as FindItemLowOrderQueryDTO),
        ...deserializeIntoLowOrderQueryDTO(findItemQueryDto as LowOrderQueryDTO),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFindPostResponse(findPostResponse: Partial<FindPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { findPostResponse.data = n.getCollectionOfObjectValues<ItemDto>(createItemDtoFromDiscriminatorValue); },
        "object": n => { findPostResponse.object = n.getEnumValue<FindPostResponse_object>(FindPostResponse_objectObject); },
        "totalElements": n => { findPostResponse.totalElements = n.getNumberValue(); },
    }
}
export interface Find400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export type FindItemQueryDto = FindItemHighOrderQueryDTO | FindItemLowOrderQueryDTO | LowOrderQueryDTO;
export interface FindPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: ItemDto[] | null;
    /**
     * The object property
     */
    object?: FindPostResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type FindPostResponse_object = (typeof FindPostResponse_objectObject)[keyof typeof FindPostResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/items/find
 */
export interface FindRequestBuilder extends BaseRequestBuilder<FindRequestBuilder> {
    /**
     * The table property
     */
    get table(): TableRequestBuilder;
    /**
     * Find a list of Item
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FindPostResponse>}
     * @throws {Find400Error} error when the service returns a 400 status code
     */
     post(body: FindItemHighOrderQueryDTO | FindItemLowOrderQueryDTO | LowOrderQueryDTO, requestConfiguration?: RequestConfiguration<FindRequestBuilderPostQueryParameters> | undefined) : Promise<FindPostResponse | undefined>;
    /**
     * Find a list of Item
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: FindItemHighOrderQueryDTO | FindItemLowOrderQueryDTO | LowOrderQueryDTO, requestConfiguration?: RequestConfiguration<FindRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Find a list of Item
 */
export interface FindRequestBuilderPostQueryParameters {
    /**
     * Level id is optional for mono level tables but mandatory in case of multi levels. It is used to target the level of the items to return.
     */
    levelId?: string;
    page?: number;
    partitionId?: string;
    size?: number;
    sort?: string;
    sortOrder?: PostSortOrderQueryParameterType;
}
export type PostSortOrderQueryParameterType = (typeof PostSortOrderQueryParameterTypeObject)[keyof typeof PostSortOrderQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFind400Error(writer: SerializationWriter, find400Error: Partial<Find400Error> | undefined | null = {}) : void {
    if (find400Error) {
        writer.writeStringValue("message", find400Error.messageEscaped);
        writer.writeAdditionalData(find400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFindItemQueryDto(writer: SerializationWriter, findItemQueryDto: Partial<FindItemHighOrderQueryDTO | FindItemLowOrderQueryDTO | LowOrderQueryDTO> | undefined | null = {}) : void {
    serializeFindItemHighOrderQueryDTO(writer, findItemQueryDto as FindItemHighOrderQueryDTO);
    serializeFindItemLowOrderQueryDTO(writer, findItemQueryDto as FindItemLowOrderQueryDTO);
    serializeLowOrderQueryDTO(writer, findItemQueryDto as LowOrderQueryDTO);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFindPostResponse(writer: SerializationWriter, findPostResponse: Partial<FindPostResponse> | undefined | null = {}) : void {
    if (findPostResponse) {
        writer.writeCollectionOfObjectValues<ItemDto>("data", findPostResponse.data, serializeItemDto);
        writer.writeEnumValue<FindPostResponse_object>("object", findPostResponse.object);
        writer.writeNumberValue("totalElements", findPostResponse.totalElements);
        writer.writeAdditionalData(findPostResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const FindRequestBuilderUriTemplate = "{+baseurl}/v1/items/find?partitionId={partitionId}{&levelId*,page*,size*,sort*,sortOrder*}";
export const FindPostResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FindRequestBuilderNavigationMetadata: Record<Exclude<keyof FindRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    table: {
        navigationMetadata: TableRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const FindRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: FindRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFind400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFindPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFindItemQueryDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
export const PostSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
/* tslint:enable */
/* eslint-enable */
