/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobDtoFromDiscriminatorValue, type JobDto } from '../../../../../models/index.js';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobDto413Error}
 */
// @ts-ignore
export function createJobDto413ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobDto413Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobDto413Error(jobDto413Error: Partial<JobDto413Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { jobDto413Error.messageEscaped = n.getStringValue(); },
    }
}
export interface JobDto413Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobDto413Error(writer: SerializationWriter, jobDto413Error: Partial<JobDto413Error> | undefined | null = {}) : void {
    if (jobDto413Error) {
        writer.writeStringValue("message", jobDto413Error.messageEscaped);
        writer.writeAdditionalData(jobDto413Error.additionalData);
    }
}
/**
 * Builds and executes requests for operations under /v1/data_factory/jobs/{id}/zip
 */
export interface ZipRequestBuilder extends BaseRequestBuilder<ZipRequestBuilder> {
    /**
     * Upload a zip to update a job
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobDto>}
     * @throws {JobDto413Error} error when the service returns a 413 status code
     */
     put(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobDto | undefined>;
    /**
     * Upload a zip to update a job
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ZipRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/jobs/{id}/zip";
/**
 * Metadata for all the requests in the request builder.
 */
export const ZipRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ZipRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            413: createJobDto413ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobDtoFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
