/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskExecutionDtoFromDiscriminatorValue, serializePatchTaskExecutionDto, serializeTaskExecutionDto, type PatchTaskExecutionDto, type TaskExecutionDto } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TaskExecutionDto400Error}
 */
// @ts-ignore
export function createTaskExecutionDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTaskExecutionDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTaskExecutionDto400Error(taskExecutionDto400Error: Partial<TaskExecutionDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { taskExecutionDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTaskExecutionDto400Error(writer: SerializationWriter, taskExecutionDto400Error: Partial<TaskExecutionDto400Error> | undefined | null = {}) : void {
    if (taskExecutionDto400Error) {
        writer.writeStringValue("message", taskExecutionDto400Error.messageEscaped);
        writer.writeAdditionalData(taskExecutionDto400Error.additionalData);
    }
}
/**
 * Builds and executes requests for operations under /v1/data_factory/task_executions/{id}
 */
export interface Task_executionsItemRequestBuilder extends BaseRequestBuilder<Task_executionsItemRequestBuilder> {
    /**
     * Get a Task Execution by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskExecutionDto>}
     * @throws {TaskExecutionDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskExecutionDto | undefined>;
    /**
     * Update running task instance
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskExecutionDto>}
     * @throws {TaskExecutionDto400Error} error when the service returns a 400 status code
     */
     patch(body: PatchTaskExecutionDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskExecutionDto | undefined>;
    /**
     * Get a Task Execution by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update running task instance
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: PatchTaskExecutionDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface TaskExecutionDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Uri template for the request builder.
 */
export const Task_executionsItemRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/task_executions/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const Task_executionsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Task_executionsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTaskExecutionDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTaskExecutionDtoFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: Task_executionsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTaskExecutionDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTaskExecutionDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePatchTaskExecutionDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
