/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuditLogDtoFromDiscriminatorValue, serializeAuditLogDto, type AuditLogDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface Audit_logs400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Audit_logsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: AuditLogDto[] | null;
    /**
     * The object property
     */
    object?: Audit_logsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type Audit_logsGetResponse_object = (typeof Audit_logsGetResponse_objectObject)[keyof typeof Audit_logsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/audit_logs
 */
export interface Audit_logsRequestBuilder extends BaseRequestBuilder<Audit_logsRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Get a list of Audit Log
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Audit_logsGetResponse>}
     * @throws {Audit_logs400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<Audit_logsRequestBuilderGetQueryParameters> | undefined) : Promise<Audit_logsGetResponse | undefined>;
    /**
     * Get a list of Audit Log
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Audit_logsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Audit Log
 */
export interface Audit_logsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Audit_logs400Error}
 */
// @ts-ignore
export function createAudit_logs400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAudit_logs400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Audit_logsGetResponse}
 */
// @ts-ignore
export function createAudit_logsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAudit_logsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAudit_logs400Error(audit_logs400Error: Partial<Audit_logs400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { audit_logs400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAudit_logsGetResponse(audit_logsGetResponse: Partial<Audit_logsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { audit_logsGetResponse.data = n.getCollectionOfObjectValues<AuditLogDto>(createAuditLogDtoFromDiscriminatorValue); },
        "object": n => { audit_logsGetResponse.object = n.getEnumValue<Audit_logsGetResponse_object>(Audit_logsGetResponse_objectObject); },
        "totalElements": n => { audit_logsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAudit_logs400Error(writer: SerializationWriter, audit_logs400Error: Partial<Audit_logs400Error> | undefined | null = {}) : void {
    if (audit_logs400Error) {
        writer.writeStringValue("message", audit_logs400Error.messageEscaped);
        writer.writeAdditionalData(audit_logs400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAudit_logsGetResponse(writer: SerializationWriter, audit_logsGetResponse: Partial<Audit_logsGetResponse> | undefined | null = {}) : void {
    if (audit_logsGetResponse) {
        writer.writeCollectionOfObjectValues<AuditLogDto>("data", audit_logsGetResponse.data, serializeAuditLogDto);
        writer.writeEnumValue<Audit_logsGetResponse_object>("object", audit_logsGetResponse.object);
        writer.writeNumberValue("totalElements", audit_logsGetResponse.totalElements);
        writer.writeAdditionalData(audit_logsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Audit_logsRequestBuilderUriTemplate = "{+baseurl}/v1/audit_logs{?page*,size*,sort*,sortOrder*}";
export const Audit_logsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Audit_logsRequestBuilderNavigationMetadata: Record<Exclude<keyof Audit_logsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Audit_logsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Audit_logsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createAudit_logs400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAudit_logsGetResponseFromDiscriminatorValue,
    },
};
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
/* tslint:enable */
/* eslint-enable */
