/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskDtoFromDiscriminatorValue, serializeTaskDto, serializeUpdateTaskDto, type TaskDto, type UpdateTaskDto } from '../../../../models/index.js';
// @ts-ignore
import { PollRequestBuilderRequestsMetadata, type PollRequestBuilder } from './poll/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TaskDto400Error}
 */
// @ts-ignore
export function createTaskDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTaskDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Tasks400Error}
 */
// @ts-ignore
export function createTasks400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTasks400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTaskDto400Error(taskDto400Error: Partial<TaskDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { taskDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTasks400Error(tasks400Error: Partial<Tasks400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { tasks400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTaskDto400Error(writer: SerializationWriter, taskDto400Error: Partial<TaskDto400Error> | undefined | null = {}) : void {
    if (taskDto400Error) {
        writer.writeStringValue("message", taskDto400Error.messageEscaped);
        writer.writeAdditionalData(taskDto400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTasks400Error(writer: SerializationWriter, tasks400Error: Partial<Tasks400Error> | undefined | null = {}) : void {
    if (tasks400Error) {
        writer.writeStringValue("message", tasks400Error.messageEscaped);
        writer.writeAdditionalData(tasks400Error.additionalData);
    }
}
export interface TaskDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Tasks400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/data_factory/tasks/{id}
 */
export interface TasksItemRequestBuilder extends BaseRequestBuilder<TasksItemRequestBuilder> {
    /**
     * The poll property
     */
    get poll(): PollRequestBuilder;
    /**
     * Delete a Task by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {Tasks400Error} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get a Task by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskDto>}
     * @throws {TaskDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskDto | undefined>;
    /**
     * Update a Task
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskDto>}
     * @throws {TaskDto400Error} error when the service returns a 400 status code
     */
     put(body: UpdateTaskDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskDto | undefined>;
    /**
     * Delete a Task by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get a Task by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update a Task
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateTaskDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TasksItemRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/tasks/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TasksItemRequestBuilderNavigationMetadata: Record<Exclude<keyof TasksItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    poll: {
        requestsMetadata: PollRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TasksItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: TasksItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTasks400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: TasksItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTaskDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTaskDtoFromDiscriminatorValue,
    },
    put: {
        uriTemplate: TasksItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTaskDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTaskDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateTaskDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
