/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeApplyAllSuggestionDto, type ApplyAllSuggestionDto } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/suggestions/{id}/apply-all
 */
export interface ApplyAllRequestBuilder extends BaseRequestBuilder<ApplyAllRequestBuilder> {
    /**
     * apply all fields and deleted fields from a suggestion
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(body: ApplyAllSuggestionDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * apply all fields and deleted fields from a suggestion
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ApplyAllSuggestionDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ApplyAllRequestBuilderUriTemplate = "{+baseurl}/v1/suggestions/{id}/apply-all";
/**
 * Metadata for all the requests in the request builder.
 */
export const ApplyAllRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ApplyAllRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeApplyAllSuggestionDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
