/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobDtoFromDiscriminatorValue, serializeJobDto, serializeUpdateJobDto, type JobDto, type UpdateJobDto } from '../../../../models/index.js';
// @ts-ignore
import { type ZipRequestBuilder, ZipRequestBuilderRequestsMetadata } from './zip/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobDto400Error}
 */
// @ts-ignore
export function createJobDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobDto400Error(jobDto400Error: Partial<JobDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { jobDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface JobDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/data_factory/jobs/{id}
 */
export interface JobsItemRequestBuilder extends BaseRequestBuilder<JobsItemRequestBuilder> {
    /**
     * The zip property
     */
    get zip(): ZipRequestBuilder;
    /**
     * Get a Job by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobDto>}
     * @throws {JobDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobDto | undefined>;
    /**
     * Update a Job
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobDto>}
     * @throws {JobDto400Error} error when the service returns a 400 status code
     */
     put(body: UpdateJobDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobDto | undefined>;
    /**
     * Get a Job by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update a Job
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateJobDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobDto400Error(writer: SerializationWriter, jobDto400Error: Partial<JobDto400Error> | undefined | null = {}) : void {
    if (jobDto400Error) {
        writer.writeStringValue("message", jobDto400Error.messageEscaped);
        writer.writeAdditionalData(jobDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const JobsItemRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/jobs/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JobsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof JobsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    zip: {
        requestsMetadata: ZipRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const JobsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: JobsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createJobDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobDtoFromDiscriminatorValue,
    },
    put: {
        uriTemplate: JobsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createJobDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateJobDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
