/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createItemLinkDtoFromDiscriminatorValue, serializeItemLinkCreateDto, serializeItemLinkDto, type ItemLinkCreateDto, type ItemLinkDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { Item_linksItemRequestBuilderRequestsMetadata, type Item_linksItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Item_links400Error}
 */
// @ts-ignore
export function createItem_links400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItem_links400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Item_linksGetResponse}
 */
// @ts-ignore
export function createItem_linksGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItem_linksGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemLinkDto400Error}
 */
// @ts-ignore
export function createItemLinkDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItemLinkDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItem_links400Error(item_links400Error: Partial<Item_links400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { item_links400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItem_linksGetResponse(item_linksGetResponse: Partial<Item_linksGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { item_linksGetResponse.data = n.getCollectionOfObjectValues<ItemLinkDto>(createItemLinkDtoFromDiscriminatorValue); },
        "object": n => { item_linksGetResponse.object = n.getEnumValue<Item_linksGetResponse_object>(Item_linksGetResponse_objectObject); },
        "totalElements": n => { item_linksGetResponse.totalElements = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemLinkDto400Error(itemLinkDto400Error: Partial<ItemLinkDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { itemLinkDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface Item_links400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Item_linksGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: ItemLinkDto[] | null;
    /**
     * The object property
     */
    object?: Item_linksGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type Item_linksGetResponse_object = (typeof Item_linksGetResponse_objectObject)[keyof typeof Item_linksGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/item_links
 */
export interface Item_linksRequestBuilder extends BaseRequestBuilder<Item_linksRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.item_links.item collection
     * @param id Unique identifier of the item
     * @returns {Item_linksItemRequestBuilder}
     */
     byId(id: string) : Item_linksItemRequestBuilder;
    /**
     * Get a list of Item link
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Item_linksGetResponse>}
     * @throws {Item_links400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<Item_linksRequestBuilderGetQueryParameters> | undefined) : Promise<Item_linksGetResponse | undefined>;
    /**
     * Create a Item link
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ItemLinkDto>}
     * @throws {ItemLinkDto400Error} error when the service returns a 400 status code
     */
     post(body: ItemLinkCreateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ItemLinkDto | undefined>;
    /**
     * Get a list of Item link
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Item_linksRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a Item link
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ItemLinkCreateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a list of Item link
 */
export interface Item_linksRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
}
export interface ItemLinkDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItem_links400Error(writer: SerializationWriter, item_links400Error: Partial<Item_links400Error> | undefined | null = {}) : void {
    if (item_links400Error) {
        writer.writeStringValue("message", item_links400Error.messageEscaped);
        writer.writeAdditionalData(item_links400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItem_linksGetResponse(writer: SerializationWriter, item_linksGetResponse: Partial<Item_linksGetResponse> | undefined | null = {}) : void {
    if (item_linksGetResponse) {
        writer.writeCollectionOfObjectValues<ItemLinkDto>("data", item_linksGetResponse.data, serializeItemLinkDto);
        writer.writeEnumValue<Item_linksGetResponse_object>("object", item_linksGetResponse.object);
        writer.writeNumberValue("totalElements", item_linksGetResponse.totalElements);
        writer.writeAdditionalData(item_linksGetResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemLinkDto400Error(writer: SerializationWriter, itemLinkDto400Error: Partial<ItemLinkDto400Error> | undefined | null = {}) : void {
    if (itemLinkDto400Error) {
        writer.writeStringValue("message", itemLinkDto400Error.messageEscaped);
        writer.writeAdditionalData(itemLinkDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Item_linksRequestBuilderUriTemplate = "{+baseurl}/v1/item_links{?page*,size*}";
export const Item_linksGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Item_linksRequestBuilderNavigationMetadata: Record<Exclude<keyof Item_linksRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: Item_linksItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Item_linksRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Item_linksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createItem_links400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createItem_linksGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: Item_linksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createItemLinkDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createItemLinkDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeItemLinkCreateDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
