/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createScreenColumnDtoFromDiscriminatorValue, type ScreenColumnDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ScreenColumnDto400Error}
 */
// @ts-ignore
export function createScreenColumnDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScreenColumnDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScreenColumnDto400Error(screenColumnDto400Error: Partial<ScreenColumnDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { screenColumnDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Builds and executes requests for operations under /v1/screen_columns/{id}
 */
export interface Screen_columnsItemRequestBuilder extends BaseRequestBuilder<Screen_columnsItemRequestBuilder> {
    /**
     * (Experimental) - Get a Screen Column by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ScreenColumnDto>}
     * @throws {ScreenColumnDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ScreenColumnDto | undefined>;
    /**
     * (Experimental) - Get a Screen Column by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface ScreenColumnDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScreenColumnDto400Error(writer: SerializationWriter, screenColumnDto400Error: Partial<ScreenColumnDto400Error> | undefined | null = {}) : void {
    if (screenColumnDto400Error) {
        writer.writeStringValue("message", screenColumnDto400Error.messageEscaped);
        writer.writeAdditionalData(screenColumnDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Screen_columnsItemRequestBuilderUriTemplate = "{+baseurl}/v1/screen_columns/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const Screen_columnsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Screen_columnsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createScreenColumnDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createScreenColumnDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
