/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFieldValueDtoFromDiscriminatorValue, serializeFieldValueDto, type FieldValueDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { Field_valuesItemRequestBuilderRequestsMetadata, type Field_valuesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Field_values400Error}
 */
// @ts-ignore
export function createField_values400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoField_values400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Field_valuesGetResponse}
 */
// @ts-ignore
export function createField_valuesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoField_valuesGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoField_values400Error(field_values400Error: Partial<Field_values400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { field_values400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoField_valuesGetResponse(field_valuesGetResponse: Partial<Field_valuesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { field_valuesGetResponse.data = n.getCollectionOfObjectValues<FieldValueDto>(createFieldValueDtoFromDiscriminatorValue); },
        "object": n => { field_valuesGetResponse.object = n.getEnumValue<Field_valuesGetResponse_object>(Field_valuesGetResponse_objectObject); },
        "totalElements": n => { field_valuesGetResponse.totalElements = n.getNumberValue(); },
    }
}
export interface Field_values400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Field_valuesGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: FieldValueDto[] | null;
    /**
     * The object property
     */
    object?: Field_valuesGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type Field_valuesGetResponse_object = (typeof Field_valuesGetResponse_objectObject)[keyof typeof Field_valuesGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/field_values
 */
export interface Field_valuesRequestBuilder extends BaseRequestBuilder<Field_valuesRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.field_values.item collection
     * @param id Unique identifier of the item
     * @returns {Field_valuesItemRequestBuilder}
     */
     byId(id: string) : Field_valuesItemRequestBuilder;
    /**
     * Get a list of Field Value
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Field_valuesGetResponse>}
     * @throws {Field_values400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<Field_valuesRequestBuilderGetQueryParameters> | undefined) : Promise<Field_valuesGetResponse | undefined>;
    /**
     * Get a list of Field Value
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Field_valuesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Field Value
 */
export interface Field_valuesRequestBuilderGetQueryParameters {
    fieldId?: string;
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeField_values400Error(writer: SerializationWriter, field_values400Error: Partial<Field_values400Error> | undefined | null = {}) : void {
    if (field_values400Error) {
        writer.writeStringValue("message", field_values400Error.messageEscaped);
        writer.writeAdditionalData(field_values400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeField_valuesGetResponse(writer: SerializationWriter, field_valuesGetResponse: Partial<Field_valuesGetResponse> | undefined | null = {}) : void {
    if (field_valuesGetResponse) {
        writer.writeCollectionOfObjectValues<FieldValueDto>("data", field_valuesGetResponse.data, serializeFieldValueDto);
        writer.writeEnumValue<Field_valuesGetResponse_object>("object", field_valuesGetResponse.object);
        writer.writeNumberValue("totalElements", field_valuesGetResponse.totalElements);
        writer.writeAdditionalData(field_valuesGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Field_valuesRequestBuilderUriTemplate = "{+baseurl}/v1/field_values?fieldId={fieldId}{&page*,size*,sort*,sortOrder*}";
export const Field_valuesGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Field_valuesRequestBuilderNavigationMetadata: Record<Exclude<keyof Field_valuesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: Field_valuesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Field_valuesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Field_valuesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createField_values400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createField_valuesGetResponseFromDiscriminatorValue,
    },
};
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
/* tslint:enable */
/* eslint-enable */
