/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AccountsRequestBuilderNavigationMetadata, AccountsRequestBuilderRequestsMetadata, type AccountsRequestBuilder } from './accounts/index.js';
// @ts-ignore
import { Comment_thread_subscribersRequestBuilderNavigationMetadata, Comment_thread_subscribersRequestBuilderRequestsMetadata, type Comment_thread_subscribersRequestBuilder } from './comment_thread_subscribers/index.js';
// @ts-ignore
import { Comment_threadsRequestBuilderNavigationMetadata, Comment_threadsRequestBuilderRequestsMetadata, type Comment_threadsRequestBuilder } from './comment_threads/index.js';
// @ts-ignore
import { Data_factoryRequestBuilderNavigationMetadata, type Data_factoryRequestBuilder } from './data_factory/index.js';
// @ts-ignore
import { Item_linksRequestBuilderNavigationMetadata, Item_linksRequestBuilderRequestsMetadata, type Item_linksRequestBuilder } from './item_links/index.js';
// @ts-ignore
import { ItemsRequestBuilderNavigationMetadata, ItemsRequestBuilderRequestsMetadata, type ItemsRequestBuilder } from './items/index.js';
// @ts-ignore
import { LevelsRequestBuilderNavigationMetadata, LevelsRequestBuilderRequestsMetadata, type LevelsRequestBuilder } from './levels/index.js';
// @ts-ignore
import { PartitionsRequestBuilderNavigationMetadata, PartitionsRequestBuilderRequestsMetadata, type PartitionsRequestBuilder } from './partitions/index.js';
// @ts-ignore
import { PublicationsRequestBuilderNavigationMetadata, PublicationsRequestBuilderRequestsMetadata, type PublicationsRequestBuilder } from './publications/index.js';
// @ts-ignore
import { ScreensRequestBuilderNavigationMetadata, ScreensRequestBuilderRequestsMetadata, type ScreensRequestBuilder } from './screens/index.js';
// @ts-ignore
import { SuggestionsRequestBuilderNavigationMetadata, SuggestionsRequestBuilderRequestsMetadata, type SuggestionsRequestBuilder } from './suggestions/index.js';
// @ts-ignore
import { TablesRequestBuilderNavigationMetadata, TablesRequestBuilderRequestsMetadata, type TablesRequestBuilder } from './tables/index.js';
// @ts-ignore
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata, UsersRequestBuilderRequestsMetadata } from './users/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1
 */
export interface V1RequestBuilder extends BaseRequestBuilder<V1RequestBuilder> {
    /**
     * The accounts property
     */
    get accounts(): AccountsRequestBuilder;
    /**
     * The comment_thread_subscribers property
     */
    get comment_thread_subscribers(): Comment_thread_subscribersRequestBuilder;
    /**
     * The comment_threads property
     */
    get comment_threads(): Comment_threadsRequestBuilder;
    /**
     * The data_factory property
     */
    get data_factory(): Data_factoryRequestBuilder;
    /**
     * The item_links property
     */
    get item_links(): Item_linksRequestBuilder;
    /**
     * The items property
     */
    get items(): ItemsRequestBuilder;
    /**
     * The levels property
     */
    get levels(): LevelsRequestBuilder;
    /**
     * The partitions property
     */
    get partitions(): PartitionsRequestBuilder;
    /**
     * The publications property
     */
    get publications(): PublicationsRequestBuilder;
    /**
     * The screens property
     */
    get screens(): ScreensRequestBuilder;
    /**
     * The suggestions property
     */
    get suggestions(): SuggestionsRequestBuilder;
    /**
     * The tables property
     */
    get tables(): TablesRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const V1RequestBuilderUriTemplate = "{+baseurl}/v1";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V1RequestBuilderNavigationMetadata: Record<Exclude<keyof V1RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    accounts: {
        requestsMetadata: AccountsRequestBuilderRequestsMetadata,
        navigationMetadata: AccountsRequestBuilderNavigationMetadata,
    },
    comment_threads: {
        requestsMetadata: Comment_threadsRequestBuilderRequestsMetadata,
        navigationMetadata: Comment_threadsRequestBuilderNavigationMetadata,
    },
    comment_thread_subscribers: {
        requestsMetadata: Comment_thread_subscribersRequestBuilderRequestsMetadata,
        navigationMetadata: Comment_thread_subscribersRequestBuilderNavigationMetadata,
    },
    data_factory: {
        navigationMetadata: Data_factoryRequestBuilderNavigationMetadata,
    },
    items: {
        requestsMetadata: ItemsRequestBuilderRequestsMetadata,
        navigationMetadata: ItemsRequestBuilderNavigationMetadata,
    },
    item_links: {
        requestsMetadata: Item_linksRequestBuilderRequestsMetadata,
        navigationMetadata: Item_linksRequestBuilderNavigationMetadata,
    },
    levels: {
        requestsMetadata: LevelsRequestBuilderRequestsMetadata,
        navigationMetadata: LevelsRequestBuilderNavigationMetadata,
    },
    partitions: {
        requestsMetadata: PartitionsRequestBuilderRequestsMetadata,
        navigationMetadata: PartitionsRequestBuilderNavigationMetadata,
    },
    publications: {
        requestsMetadata: PublicationsRequestBuilderRequestsMetadata,
        navigationMetadata: PublicationsRequestBuilderNavigationMetadata,
    },
    screens: {
        requestsMetadata: ScreensRequestBuilderRequestsMetadata,
        navigationMetadata: ScreensRequestBuilderNavigationMetadata,
    },
    suggestions: {
        requestsMetadata: SuggestionsRequestBuilderRequestsMetadata,
        navigationMetadata: SuggestionsRequestBuilderNavigationMetadata,
    },
    tables: {
        requestsMetadata: TablesRequestBuilderRequestsMetadata,
        navigationMetadata: TablesRequestBuilderNavigationMetadata,
    },
    users: {
        requestsMetadata: UsersRequestBuilderRequestsMetadata,
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
