/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTableDtoFromDiscriminatorValue, type TableDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TableDto400Error}
 */
// @ts-ignore
export function createTableDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTableDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTableDto400Error(tableDto400Error: Partial<TableDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { tableDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTableDto400Error(writer: SerializationWriter, tableDto400Error: Partial<TableDto400Error> | undefined | null = {}) : void {
    if (tableDto400Error) {
        writer.writeStringValue("message", tableDto400Error.messageEscaped);
        writer.writeAdditionalData(tableDto400Error.additionalData);
    }
}
export interface TableDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/tables/{id}
 */
export interface TablesItemRequestBuilder extends BaseRequestBuilder<TablesItemRequestBuilder> {
    /**
     * Get a Table by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TableDto>}
     * @throws {TableDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TableDto | undefined>;
    /**
     * Get a Table by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TablesItemRequestBuilderUriTemplate = "{+baseurl}/v1/tables/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const TablesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TablesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createTableDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTableDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
