/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSectionDtoFromDiscriminatorValue, serializeSectionDto, type SectionDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { SectionsItemRequestBuilderRequestsMetadata, type SectionsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Sections400Error}
 */
// @ts-ignore
export function createSections400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSections400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SectionsGetResponse}
 */
// @ts-ignore
export function createSectionsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSectionsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSections400Error(sections400Error: Partial<Sections400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { sections400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSectionsGetResponse(sectionsGetResponse: Partial<SectionsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { sectionsGetResponse.data = n.getCollectionOfObjectValues<SectionDto>(createSectionDtoFromDiscriminatorValue); },
        "object": n => { sectionsGetResponse.object = n.getEnumValue<SectionsGetResponse_object>(SectionsGetResponse_objectObject); },
        "totalElements": n => { sectionsGetResponse.totalElements = n.getNumberValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
export interface Sections400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface SectionsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: SectionDto[] | null;
    /**
     * The object property
     */
    object?: SectionsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type SectionsGetResponse_object = (typeof SectionsGetResponse_objectObject)[keyof typeof SectionsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/sections
 */
export interface SectionsRequestBuilder extends BaseRequestBuilder<SectionsRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.sections.item collection
     * @param id Unique identifier of the item
     * @returns {SectionsItemRequestBuilder}
     */
     byId(id: string) : SectionsItemRequestBuilder;
    /**
     * Get a list of Section
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SectionsGetResponse>}
     * @throws {Sections400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<SectionsRequestBuilderGetQueryParameters> | undefined) : Promise<SectionsGetResponse | undefined>;
    /**
     * Get a list of Section
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SectionsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Section
 */
export interface SectionsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
    tableId?: string;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSections400Error(writer: SerializationWriter, sections400Error: Partial<Sections400Error> | undefined | null = {}) : void {
    if (sections400Error) {
        writer.writeStringValue("message", sections400Error.messageEscaped);
        writer.writeAdditionalData(sections400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSectionsGetResponse(writer: SerializationWriter, sectionsGetResponse: Partial<SectionsGetResponse> | undefined | null = {}) : void {
    if (sectionsGetResponse) {
        writer.writeCollectionOfObjectValues<SectionDto>("data", sectionsGetResponse.data, serializeSectionDto);
        writer.writeEnumValue<SectionsGetResponse_object>("object", sectionsGetResponse.object);
        writer.writeNumberValue("totalElements", sectionsGetResponse.totalElements);
        writer.writeAdditionalData(sectionsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const SectionsRequestBuilderUriTemplate = "{+baseurl}/v1/sections?tableId={tableId}{&page*,size*,sort*,sortOrder*}";
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
export const SectionsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SectionsRequestBuilderNavigationMetadata: Record<Exclude<keyof SectionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: SectionsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SectionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SectionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createSections400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSectionsGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
