/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Task_executionsItemRequestBuilderRequestsMetadata, type Task_executionsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/data_factory/task_executions
 */
export interface Task_executionsRequestBuilder extends BaseRequestBuilder<Task_executionsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.data_factory.task_executions.item collection
     * @param id Unique identifier of the item
     * @returns {Task_executionsItemRequestBuilder}
     */
     byId(id: string) : Task_executionsItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const Task_executionsRequestBuilderUriTemplate = "{+baseurl}/v1/data_factory/task_executions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Task_executionsRequestBuilderNavigationMetadata: Record<Exclude<keyof Task_executionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: Task_executionsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
