/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPublicationDtoFromDiscriminatorValue, serializePatchPublicationDto, type PatchPublicationDto, type PublicationDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicationDto400Error}
 */
// @ts-ignore
export function createPublicationDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicationDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Publications400Error}
 */
// @ts-ignore
export function createPublications400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublications400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicationDto400Error(publicationDto400Error: Partial<PublicationDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { publicationDto400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublications400Error(publications400Error: Partial<Publications400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { publications400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface PublicationDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Publications400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/publications/{id}
 */
export interface PublicationsItemRequestBuilder extends BaseRequestBuilder<PublicationsItemRequestBuilder> {
    /**
     * Get a Publication by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PublicationDto>}
     * @throws {PublicationDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PublicationDto | undefined>;
    /**
     * (Experimental) - Update the status of a publication
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {Publications400Error} error when the service returns a 400 status code
     */
     patch(body: PatchPublicationDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Get a Publication by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * (Experimental) - Update the status of a publication
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: PatchPublicationDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicationDto400Error(writer: SerializationWriter, publicationDto400Error: Partial<PublicationDto400Error> | undefined | null = {}) : void {
    if (publicationDto400Error) {
        writer.writeStringValue("message", publicationDto400Error.messageEscaped);
        writer.writeAdditionalData(publicationDto400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublications400Error(writer: SerializationWriter, publications400Error: Partial<Publications400Error> | undefined | null = {}) : void {
    if (publications400Error) {
        writer.writeStringValue("message", publications400Error.messageEscaped);
        writer.writeAdditionalData(publications400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const PublicationsItemRequestBuilderUriTemplate = "{+baseurl}/v1/publications/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PublicationsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PublicationsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createPublicationDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPublicationDtoFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: PublicationsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createPublications400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePatchPublicationDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
