/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LevelRequestBuilderNavigationMetadata, type LevelRequestBuilder } from './level/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/items/find/table/{tableId}/partition/{partitionId}
 */
export interface WithPartitionItemRequestBuilder extends BaseRequestBuilder<WithPartitionItemRequestBuilder> {
    /**
     * The level property
     */
    get level(): LevelRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithPartitionItemRequestBuilderUriTemplate = "{+baseurl}/v1/items/find/table/{tableId}/partition/{partitionId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithPartitionItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithPartitionItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    level: {
        navigationMetadata: LevelRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
