/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ErrorRequestBuilderRequestsMetadata, type ErrorRequestBuilder } from './errorEscaped/index.js';
// @ts-ignore
import { LivenessRequestBuilderRequestsMetadata, type LivenessRequestBuilder } from './liveness/index.js';
// @ts-ignore
import { ReadinessRequestBuilderRequestsMetadata, type ReadinessRequestBuilder } from './readiness/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /probe
 */
export interface ProbeRequestBuilder extends BaseRequestBuilder<ProbeRequestBuilder> {
    /**
     * The error property
     */
    get errorEscaped(): ErrorRequestBuilder;
    /**
     * The liveness property
     */
    get liveness(): LivenessRequestBuilder;
    /**
     * The readiness property
     */
    get readiness(): ReadinessRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProbeRequestBuilderUriTemplate = "{+baseurl}/probe";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProbeRequestBuilderNavigationMetadata: Record<Exclude<keyof ProbeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    errorEscaped: {
        requestsMetadata: ErrorRequestBuilderRequestsMetadata,
    },
    liveness: {
        requestsMetadata: LivenessRequestBuilderRequestsMetadata,
    },
    readiness: {
        requestsMetadata: ReadinessRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
