/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFieldDtoFromDiscriminatorValue, serializeFieldDto, serializeFieldUpdateDto, type FieldDto, type FieldUpdateDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FieldDto400Error}
 */
// @ts-ignore
export function createFieldDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFieldDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFieldDto400Error(fieldDto400Error: Partial<FieldDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { fieldDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export interface FieldDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Builds and executes requests for operations under /v1/fields/{id}
 */
export interface FieldsItemRequestBuilder extends BaseRequestBuilder<FieldsItemRequestBuilder> {
    /**
     * Get a Field by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FieldDto>}
     * @throws {FieldDto400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FieldDto | undefined>;
    /**
     * Patch a Field
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FieldDto>}
     * @throws {FieldDto400Error} error when the service returns a 400 status code
     */
     patch(body: FieldUpdateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FieldDto | undefined>;
    /**
     * Get a Field by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Patch a Field
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: FieldUpdateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFieldDto400Error(writer: SerializationWriter, fieldDto400Error: Partial<FieldDto400Error> | undefined | null = {}) : void {
    if (fieldDto400Error) {
        writer.writeStringValue("message", fieldDto400Error.messageEscaped);
        writer.writeAdditionalData(fieldDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const FieldsItemRequestBuilderUriTemplate = "{+baseurl}/v1/fields/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const FieldsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FieldsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFieldDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFieldDtoFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: FieldsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFieldDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFieldDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFieldUpdateDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
