/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithLevelItemRequestBuilder, WithLevelItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/items/find/table/{tableId}/partition/{partitionId}/level
 */
export interface LevelRequestBuilder extends BaseRequestBuilder<LevelRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.items.find.table.item.partition.item.level.item collection
     * @param levelId Unique identifier of the item
     * @returns {WithLevelItemRequestBuilder}
     * @deprecated 
     */
     byLevelId(levelId: string) : WithLevelItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const LevelRequestBuilderUriTemplate = "{+baseurl}/v1/items/find/table/{tableId}/partition/{partitionId}/level";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LevelRequestBuilderNavigationMetadata: Record<Exclude<keyof LevelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLevelId: {
        requestsMetadata: WithLevelItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["levelId"],
    },
};
/* tslint:enable */
/* eslint-enable */
