/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCommentThreadDtoFromDiscriminatorValue, serializeCommentThreadCreateDto, serializeCommentThreadDto, type CommentThreadCreateDto, type CommentThreadDto } from '../../models/index.js';
// @ts-ignore
import { FindRequestBuilderRequestsMetadata, type FindRequestBuilder } from './find/index.js';
// @ts-ignore
import { Comment_threadsItemRequestBuilderNavigationMetadata, Comment_threadsItemRequestBuilderRequestsMetadata, type Comment_threadsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface Comment_threads400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface Comment_threadsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The data property
     */
    data?: CommentThreadDto[] | null;
    /**
     * The object property
     */
    object?: Comment_threadsGetResponse_object | null;
    /**
     * The totalElements property
     */
    totalElements?: number | null;
}
export type Comment_threadsGetResponse_object = (typeof Comment_threadsGetResponse_objectObject)[keyof typeof Comment_threadsGetResponse_objectObject];
/**
 * Builds and executes requests for operations under /v1/comment_threads
 */
export interface Comment_threadsRequestBuilder extends BaseRequestBuilder<Comment_threadsRequestBuilder> {
    /**
     * The find property
     */
    get find(): FindRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.comment_threads.item collection
     * @param id Unique identifier of the item
     * @returns {Comment_threadsItemRequestBuilder}
     */
     byId(id: string) : Comment_threadsItemRequestBuilder;
    /**
     * Get a list of Comment Thread
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Comment_threadsGetResponse>}
     * @throws {Comment_threads400Error} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<Comment_threadsRequestBuilderGetQueryParameters> | undefined) : Promise<Comment_threadsGetResponse | undefined>;
    /**
     * Create a Comment Thread
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CommentThreadDto>}
     * @throws {CommentThreadDto400Error} error when the service returns a 400 status code
     */
     post(body: CommentThreadCreateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CommentThreadDto | undefined>;
    /**
     * Get a list of Comment Thread
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Comment_threadsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a Comment Thread
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CommentThreadCreateDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a list of Comment Thread
 */
export interface Comment_threadsRequestBuilderGetQueryParameters {
    page?: number;
    size?: number;
    sort?: string;
    sortOrder?: GetSortOrderQueryParameterType;
}
export interface CommentThreadDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Comment_threads400Error}
 */
// @ts-ignore
export function createComment_threads400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoComment_threads400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Comment_threadsGetResponse}
 */
// @ts-ignore
export function createComment_threadsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoComment_threadsGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CommentThreadDto400Error}
 */
// @ts-ignore
export function createCommentThreadDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCommentThreadDto400Error;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoComment_threads400Error(comment_threads400Error: Partial<Comment_threads400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { comment_threads400Error.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoComment_threadsGetResponse(comment_threadsGetResponse: Partial<Comment_threadsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { comment_threadsGetResponse.data = n.getCollectionOfObjectValues<CommentThreadDto>(createCommentThreadDtoFromDiscriminatorValue); },
        "object": n => { comment_threadsGetResponse.object = n.getEnumValue<Comment_threadsGetResponse_object>(Comment_threadsGetResponse_objectObject); },
        "totalElements": n => { comment_threadsGetResponse.totalElements = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCommentThreadDto400Error(commentThreadDto400Error: Partial<CommentThreadDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { commentThreadDto400Error.messageEscaped = n.getStringValue(); },
    }
}
export type GetSortOrderQueryParameterType = (typeof GetSortOrderQueryParameterTypeObject)[keyof typeof GetSortOrderQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeComment_threads400Error(writer: SerializationWriter, comment_threads400Error: Partial<Comment_threads400Error> | undefined | null = {}) : void {
    if (comment_threads400Error) {
        writer.writeStringValue("message", comment_threads400Error.messageEscaped);
        writer.writeAdditionalData(comment_threads400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeComment_threadsGetResponse(writer: SerializationWriter, comment_threadsGetResponse: Partial<Comment_threadsGetResponse> | undefined | null = {}) : void {
    if (comment_threadsGetResponse) {
        writer.writeCollectionOfObjectValues<CommentThreadDto>("data", comment_threadsGetResponse.data, serializeCommentThreadDto);
        writer.writeEnumValue<Comment_threadsGetResponse_object>("object", comment_threadsGetResponse.object);
        writer.writeNumberValue("totalElements", comment_threadsGetResponse.totalElements);
        writer.writeAdditionalData(comment_threadsGetResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCommentThreadDto400Error(writer: SerializationWriter, commentThreadDto400Error: Partial<CommentThreadDto400Error> | undefined | null = {}) : void {
    if (commentThreadDto400Error) {
        writer.writeStringValue("message", commentThreadDto400Error.messageEscaped);
        writer.writeAdditionalData(commentThreadDto400Error.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const Comment_threadsRequestBuilderUriTemplate = "{+baseurl}/v1/comment_threads{?page*,size*,sort*,sortOrder*}";
export const Comment_threadsGetResponse_objectObject = {
    List: "list",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Comment_threadsRequestBuilderNavigationMetadata: Record<Exclude<keyof Comment_threadsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: Comment_threadsItemRequestBuilderRequestsMetadata,
        navigationMetadata: Comment_threadsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    find: {
        requestsMetadata: FindRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Comment_threadsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Comment_threadsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createComment_threads400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createComment_threadsGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: Comment_threadsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createCommentThreadDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCommentThreadDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCommentThreadCreateDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
export const GetSortOrderQueryParameterTypeObject = {
    DESC: "DESC",
    ASC: "ASC",
} as const;
/* tslint:enable */
/* eslint-enable */
